Repository apache/shardingsphere-elasticjob, pull requests merged in 2020-07, with the labels that each got.

#875 db2 sql commit
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/resources/META-INF/sql/db2.properties
Labels: enhancement, tracing

#876 Separate registerJob and registerRegistryCenter
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobRegistry.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/JobSchedulerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/RescheduleListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/election/ElectionListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/election/LeaderServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/ShutdownListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/TriggerListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/listener/RegistryCenterConnectionStateListenerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobRegistryTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/SchedulerFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/server/ServerServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingServiceTest.java
Labels: refactor

#880 Refactor cron from required to optional in job config
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/JobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/yaml/YamlJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/config/JobConfigurationTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/DataflowJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/ScriptJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/SimpleJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/WrongJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/util/JobConfigurationUtil.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/AbstractBaseStdJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/yaml/YamlJobConfigurationTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/monitor/MonitorServiceEnableTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/reconcile/ReconcileServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/SetUpFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionContextServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingServiceTest.java
  examples/elastic-job-example-lite-java/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/JavaMain.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/DataflowJobConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/SimpleJobConfig.java
Labels: enhancement

#881 Fixed FailoverListenerManager cause NPE(#860)
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManager.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManagerTest.java
Labels: bug

#882 Dev
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/JobBootstrap.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/OneOffJobBootstrap.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/ScheduleJobBootstrap.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/BaseIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/DisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/EnabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/disable/oneoff/OneOffDisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/disable/schedule/ScheduleDisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/OneOffDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobForExecuteFailureTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobForExecuteThrowsExceptionTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobForMultipleThreadsTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobForNotMonitorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/script/ScriptElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/simple/SimpleElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/OneOffDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobForExecuteFailureTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobForExecuteThrowsExceptionTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobForMultipleThreadsTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobForNotMonitorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/script/ScriptElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/simple/SimpleElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/monitor/BaseMonitorServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/monitor/MonitorServiceDisableTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/monitor/MonitorServiceEnableTest.java
Labels: test

#883 Separate one-off and schedule job's execute interface
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/JobBootstrap.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/OneOffJobBootstrap.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/ScheduleJobBootstrap.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/BaseIntegrateTest.java
Labels: enhancement

#885 Adapt spring namespace
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/common/AbstractJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/resources/META-INF/namespace/job.xsd
  elastic-job-lite-spring/src/test/java/org/apache/shardingsphere/elasticjob/lite/spring/job/AbstractJobSpringIntegrateTest.java
  elastic-job-lite-spring/src/test/java/org/apache/shardingsphere/elasticjob/lite/spring/job/JobSpringNamespaceWithRefTest.java
Labels: enhancement, spring

#891 Remove job monitor port config from console
  elastic-job-lite-console/src/main/resources/console/html/status/job/job_config.html
  elastic-job-lite-console/src/main/resources/console/i18n/message_en.properties
  elastic-job-lite-console/src/main/resources/console/i18n/message_zh.properties
  elastic-job-lite-console/src/main/resources/console/js/status/job/job_config.js
  elastic-job-lite-console/src/main/resources/console/js/status/job/jobs_status_overview.js
Labels: ui

#893 Update company
  docs/content/00-overview/company.md
Labels: document

#895 Update website url
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/question.md
  README.md
Labels: document

#892 Associated original data source switching for spring boot
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/config/DynamicDataSourceConfig.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/domain/DataSourceFactory.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/domain/EventTraceDataSourceConfiguration.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/domain/EventTraceDataSourceFactory.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/impl/EventTraceDataSourceConfigurationServiceImpl.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/util/SessionEventTraceDataSourceConfiguration.java
Labels: console

#894 add [exec] in concole start.sh(#503)
  elastic-job-lite-console/src/main/resources/bin/start.sh
Labels: console, enhancement

#884 Use spring boot + JPA to deal with search dao
  elastic-job-lite-console/pom.xml
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/EventTraceHistoryController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/JobExecutionLog.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/JobExecutionLogRepository.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/JobStatusTraceLog.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/JobStatusTraceLogRepository.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearch.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/util/BeanUtils.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearchTest.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearchTestConfiguration.java
Labels: console

#896 Update company
  docs/content/00-overview/company.md
Labels: document

#897 Add apache copyright and revise for code style
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/config/DynamicDataSourceConfig.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/config/advice/ConsoleRestControllerAdvice.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/EventTraceHistoryController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/JobOperationController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/RegistryCenterController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/JobExecutionLogRepository.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/JobStatusTraceLogRepository.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/JobRegisterStatisticsRepository.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/JobRunningStatisticsRepository.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/StatisticInterval.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/TaskResultStatisticsRepository.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/TaskRunningStatisticsRepository.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/domain/DataSourceFactory.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/domain/JobRegisterStatistics.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/domain/JobRunningStatistics.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/domain/TaskResultStatistics.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/domain/TaskRunningStatistics.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/JobAPIService.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/impl/EventTraceDataSourceConfigurationServiceImpl.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/util/HomeFolderUtils.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/util/SessionEventTraceDataSourceConfiguration.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearchTest.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearchTestConfiguration.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/rdb/RDBStatisticRepositoryTest.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/util/HomeFolderUtilsTest.java
Labels: console, refactor

#903 The data source cannot be created due to a file path problem
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/util/HomeFolderUtils.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/util/HomeFolderUtilsTest.java
Labels: console

#907 Update console version
  elastic-job-lite-console/src/main/resources/console/index.html
Labels: console

#910 Use echo instead of test.bat and test.sh for test cases
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/util/ScriptElasticJobUtil.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/script/ScriptElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/script/ScriptElasticJobTest.java
  elastic-job-lite-core/src/test/resources/script/test.bat
  elastic-job-lite-core/src/test/resources/script/test.sh
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/fixture/LifecycleYamlConstants.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImplTest.java
Labels: test

#911 Update powered by page
  docs/content/00-overview/powered-by.md
Labels: document

#912 modify sql92
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/resources/META-INF/sql/sql92.properties
Labels: enhancement, tracing

#913 Decouple job type and facade class
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/JobFacade.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/DataflowJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacade.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/DataflowJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacadeTest.java
Labels: API, refactor

#916 Remove JobType
  elastic-job-lite-console/src/main/resources/console/html/status/job/job_config.html
  elastic-job-lite-console/src/main/resources/console/i18n/message_en.properties
  elastic-job-lite-console/src/main/resources/console/i18n/message_zh.properties
  elastic-job-lite-console/src/main/resources/console/js/status/job/job_config.js
  elastic-job-lite-console/src/main/resources/console/js/status/job/jobs_status_overview.js
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/type/JobType.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/JobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/yaml/YamlJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/config/JobConfigurationTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/DataflowJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/SimpleJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/WrongJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/LiteYamlConstants.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/util/JobConfigurationUtil.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/disable/oneoff/OneOffDisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/disable/schedule/ScheduleDisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/OneOffDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobForExecuteFailureTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobForExecuteThrowsExceptionTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobForMultipleThreadsTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobForNotMonitorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/script/ScriptElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/simple/SimpleElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/OneOffDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobForExecuteFailureTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobForExecuteThrowsExceptionTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobForMultipleThreadsTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobForNotMonitorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/script/ScriptElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/simple/SimpleElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/yaml/YamlJobConfigurationTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/monitor/BaseMonitorServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/reconcile/ReconcileServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/SetUpFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionContextServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/util/yaml/YamlEngineTest.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/domain/JobSettings.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImpl.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/fixture/LifecycleYamlConstants.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImplTest.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/common/AbstractJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/dataflow/DataflowJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/script/ScriptJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/simple/SimpleJobBeanDefinitionParser.java
  examples/elastic-job-example-lite-java/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/JavaMain.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/DataflowJobConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/SimpleJobConfig.java
Labels: API, refactor

#915 fix member variable access modifiers.
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/election/LeaderNode.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverNode.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeNode.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingNode.java
Labels: refactor

#918 Remove useless ScriptJob interface
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/type/script/ScriptJob.java
Labels: refactor

#919 Refactor TypedJob for not SimpleJob only
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/job/TypedJob.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/job/impl/ScriptJob.java
Labels: refactor

#925 Decouple JobBootstrap with OneOffJobBootstrap and ScheduleJobBootstrap
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/JobBootstrap.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/OneOffJobBootstrap.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/ScheduleJobBootstrap.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/scheduler/JobScheduler.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/BaseIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/DisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobForExecuteFailureTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobForExecuteThrowsExceptionTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobForMultipleThreadsTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowElasticJobForNotMonitorTest.java
Labels: API, refactor

#927 Fix JobOperationController bug
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/JobOperationController.java
Labels: console

#930 Refactor EventTraceHistoryController
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/EventTraceHistoryController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/JobExecutionLogRepository.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/JobStatusTraceLogRepository.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearch.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/domain/JobExecutionLog.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/domain/JobStatusTraceLog.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dto/request/BasePageRequest.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dto/request/FindJobExecutionEventsRequest.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dto/request/FindJobStatusTraceEventsRequest.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dto/response/BasePageResponse.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/EventTraceHistoryService.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/impl/EventTraceHistoryServiceImpl.java
  elastic-job-lite-console/src/main/resources/application.properties
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearchTest.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearchTestConfiguration.java
Labels: console, refactor

#931 For code format
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/EventTraceHistoryController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/RegistryCenterController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dto/request/BasePageRequest.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dto/request/FindJobExecutionEventsRequest.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dto/request/FindJobStatusTraceEventsRequest.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dto/response/BasePageResponse.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/EventTraceHistoryService.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/impl/EventTraceHistoryServiceImpl.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearchTest.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearchTestConfiguration.java
Labels: console, refactor

#936 Update powered by page
  docs/content/00-overview/powered-by.md
Labels: document

#938 Remove -XX:-UseSplitVerifier for mvn install
  pom.xml
Labels: build

#939 Replace JobSettings to YamlJobConfiguration #866
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/JobConfigController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/JobAPIService.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/impl/JobAPIServiceImpl.java
  elastic-job-lite-console/src/main/resources/console/js/status/job/job_config.js
  elastic-job-lite-console/src/main/resources/console/js/status/job/jobs_status_overview.js
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/api/JobAPIFactory.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/api/JobConfigAPI.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/domain/JobSettings.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobConfigAPIImpl.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImpl.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/api/JobAPIFactoryTest.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobConfigAPIImplTest.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImplTest.java
Labels: console

#941 Revise #939
  docs/content/02-guide/operation-manual.md
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/JobConfigController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/JobAPIService.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/impl/JobAPIServiceImpl.java
  elastic-job-lite-console/src/main/resources/console/js/status/job/job_config.js
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/api/JobAPIFactory.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/api/JobConfigurationAPI.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobConfigurationAPIImpl.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/api/JobAPIFactoryTest.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobConfigurationAPIImplTest.java
Labels: console, refactor

#942 Remove and merge useless test fixture
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/job/ShardingContextTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/ShardingContextsBuilder.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/TestDataflowJob.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/TestSimpleJob.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/context/TaskNode.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/util/JobConfigurationUtil.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/SetUpFacadeTest.java
Labels: test

#945 Decouple simple job and monitor service test
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/DisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/simple/SimpleElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/simple/SimpleElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/fixture/simple/FooSimpleJob.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/monitor/BaseMonitorServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/monitor/MonitorServiceDisableTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/monitor/MonitorServiceEnableTest.java
Labels: test

#947 Fix issue for disable job in startup is not in effect sometimes
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/server/ServerService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/server/ServerStatus.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/BaseIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/DisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/server/ServerServiceTest.java
Labels: bug

#949 Fixes #948
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/BaseIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/DisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/disable/OneOffDisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/disable/ScheduleDisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/BatchDataflowJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/simple/SimpleElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/BatchDataflowJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/OneOffDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobForExecuteFailureTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobForNotMonitorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/simple/SimpleElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/fixture/dataflow/BatchDataflowJob.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/fixture/dataflow/StreamingDataflowElasticJob.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/fixture/dataflow/StreamingDataflowElasticJobForExecuteFailure.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/fixture/dataflow/StreamingDataflowJob.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/fixture/simple/FooSimpleJob.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/reg/zookeeper/ZookeeperRegistryCenterQueryWithoutCacheTest.java
Labels: test

#951 Fixes #950
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/BaseIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/DisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/EnabledJobIntegrateTest.java
Labels: test

#952 Refactor integrate test's sturcture
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/JobItemExecutorFactoryTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/executor/ClassedFooJobExecutor.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/executor/TypedFooJobExecutor.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/job/DetailedFooJob.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/job/FailedJob.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/job/FooJob.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/BaseIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/disable/DisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/disable/OneOffDisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/disable/ScheduleDisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/EnabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/OneOffEnabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/ScheduleEnabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/dataflow/StreamingDataflowJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/script/ScriptElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/oneoff/simple/SimpleElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/dataflow/StreamingDataflowJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/script/ScriptElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/assertion/enable/schedule/simple/SimpleElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/monitor/MonitorServiceDisableTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/monitor/MonitorServiceEnableTest.java
  elastic-job-lite-core/src/test/resources/META-INF/services/org.apache.shardingsphere.elasticjob.lite.executor.type.JobItemExecutor
Labels: test

#956 Move JobScheduler to internal package
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/impl/OneOffJobBootstrap.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/impl/ScheduleJobBootstrap.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobScheduler.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/job/JobConfigurationTest.java
Labels: refactor

#957 Rename package name form executor.type to executor.item
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/item/JobItemExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/item/JobItemExecutorFactory.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/item/impl/ClassedJobItemExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/item/impl/TypedJobItemExecutor.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/item/JobItemExecutorFactoryTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/executor/ClassedFooJobExecutor.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/executor/TypedFooJobExecutor.java
  elastic-job-lite-core/src/test/resources/META-INF/services/org.apache.shardingsphere.elasticjob.lite.executor.item.JobItemExecutor
  elastic-job-lite-executor/elastic-job-lite-dataflow-executor/src/main/java/org/apache/shardingsphere/elasticjob/lite/dataflow/executor/DataflowJobExecutor.java
  elastic-job-lite-executor/elastic-job-lite-dataflow-executor/src/main/resources/META-INF/services/org.apache.shardingsphere.elasticjob.lite.executor.item.JobItemExecutor
  elastic-job-lite-executor/elastic-job-lite-script-executor/src/main/java/org/apache/shardingsphere/elasticjob/lite/script/executor/ScriptJobExecutor.java
  elastic-job-lite-executor/elastic-job-lite-script-executor/src/main/resources/META-INF/services/org.apache.shardingsphere.elasticjob.lite.executor.item.JobItemExecutor
  elastic-job-lite-executor/elastic-job-lite-simple-executor/src/main/java/org/apache/shardingsphere/elasticjob/lite/simple/executor/SimpleJobExecutor.java
  elastic-job-lite-executor/elastic-job-lite-simple-executor/src/main/resources/META-INF/services/org.apache.shardingsphere.elasticjob.lite.executor.item.JobItemExecutor
Labels: refactor

#959 Fix the job can not enable for disabled job integrate test sometimes
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/listener/AbstractDistributeOnceElasticJobListener.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeService.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/listener/DistributeOnceElasticJobListenerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/disable/ScheduleDisabledJobIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeServiceTest.java
Labels: bug

#966 Thin code
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/listener/AbstractDistributeOnceElasticJobListener.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/disable/ScheduleDisabledJobIntegrateTest.java
Labels: refactor

#969 Merge namespace prefix to elasticjob
  README.md
  README_ZH.md
  docs/content/00-overview/intro.md
  docs/content/01-start/dev-guide.md
  docs/content/01-start/quick-start.md
  docs/content/02-guide/config-manual.md
  docs/content/02-guide/dump.md
  docs/content/02-guide/job-reconcile.md
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/ElasticJobNamespaceHandler.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/monitor/handler/MonitorNamespaceHandler.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/reg/handler/RegNamespaceHandler.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/tracing/handler/TracingNamespaceHandler.java
  elastic-job-lite-spring/src/main/resources/META-INF/namespace/elasticjob.xsd
  elastic-job-lite-spring/src/main/resources/META-INF/namespace/monitor.xsd
  elastic-job-lite-spring/src/main/resources/META-INF/namespace/reg.xsd
  elastic-job-lite-spring/src/main/resources/META-INF/namespace/tracing.xsd
  elastic-job-lite-spring/src/main/resources/META-INF/spring.handlers
  elastic-job-lite-spring/src/main/resources/META-INF/spring.schemas
  elastic-job-lite-spring/src/test/resources/META-INF/job/base.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withEventTraceRdb.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withJobHandler.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withJobRef.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withListener.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withListenerAndCglib.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withListenerAndJdkDynamicProxy.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withoutListener.xml
  elastic-job-lite-spring/src/test/resources/META-INF/reg/regContext.xml
  examples/elastic-job-example-lite-spring/src/main/resources/META-INF/applicationContext.xml
Labels: API, refactor, spring

#975 Fix weight typo of doc
  docs/content/start/deploy-guide.en.md
Labels: document

#976 Consider about rename monitor service
  README.md
  README_ZH.md
  docs/content/guide/dump.cn.md
  docs/content/guide/dump.en.md
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SnapshotService.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/BaseSnapshotServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SnapshotServiceDisableTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SnapshotServiceEnableTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SocketUtils.java
  elastic-job-lite-core/src/test/resources/logback-test.xml
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/ElasticJobNamespaceHandler.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/snapshot/parser/SnapshotBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/snapshot/tag/SnapshotBeanDefinitionTag.java
  elastic-job-lite-spring/src/main/resources/META-INF/namespace/elasticjob.xsd
  examples/elastic-job-example-lite-spring/src/main/resources/META-INF/applicationContext.xml
Labels: refactor

#979 add postgresQL.properties for tracing event in sql config (#972)
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/resources/META-INF/sql/postgresQL.properties
Labels: enhancement, tracing

#978 Add test case for snapshot spring namespace
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SnapshotService.java
  elastic-job-lite-spring/src/test/java/org/apache/shardingsphere/elasticjob/lite/spring/snapshot/SnapshotSpringNamespaceDisableTest.java
  elastic-job-lite-spring/src/test/java/org/apache/shardingsphere/elasticjob/lite/spring/snapshot/SnapshotSpringNamespaceEnableTest.java
  elastic-job-lite-spring/src/test/java/org/apache/shardingsphere/elasticjob/lite/spring/snapshot/SocketUtils.java
  elastic-job-lite-spring/src/test/resources/META-INF/snapshot/snapshotDisabled.xml
  elastic-job-lite-spring/src/test/resources/META-INF/snapshot/snapshotEnabled.xml
Labels: spring, test

#980 fix the issue that the elastic job console decode the password with Base64, which is not safety!
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/security/UserAuthenticationService.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/security/WwwAuthFilter.java
Labels: console

#985 Adjust powered-by URL
  docs/content/powered-by/_index.cn.md
  docs/content/powered-by/_index.en.md
Labels: document

#981 Fix the demo which doesn't work properly.
  examples/elastic-job-example-lite-springboot/pom.xml
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/DataflowJobConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/SimpleJobConfig.java
Labels: example

#986 change title from shardingsphere to elasticjob
  docs/config.toml
Labels: document

#989 Add blog URL
  docs/content/blog/_index.cn.md
  docs/content/blog/_index.en.md
  docs/content/overview/contribution.cn.md
  docs/content/overview/contribution.en.md
Labels: document

#990 update blog index
  docs/content/blog/_index.cn.md
  docs/content/blog/_index.en.md
Labels: document

#993 Add todo for english doc
  docs/content/blog/_index.en.md
  docs/content/dev-manual/_index.cn.md
  docs/content/dev-manual/_index.en.md
  docs/content/dev-manual/lite-design.en.md
  docs/content/faq/_index.en.md
  docs/content/features/elastic.en.md
  docs/content/powered-by/_index.en.md
  docs/content/quick-start/_index.en.md
  docs/content/user-manual/_index.cn.md
  docs/content/user-manual/customized-hook.cn.md
  docs/content/user-manual/customized-hook.en.md
  docs/content/user-manual/deploy-guide.cn.md
  docs/content/user-manual/deploy-guide.en.md
  docs/content/user-manual/dump.cn.md
  docs/content/user-manual/dump.en.md
  docs/content/user-manual/event-trace.cn.md
  docs/content/user-manual/event-trace.en.md
  docs/content/user-manual/execution-monitor.cn.md
  docs/content/user-manual/execution-monitor.en.md
  docs/content/user-manual/job-api.en.md
  docs/content/user-manual/job-config.en.md
  docs/content/user-manual/job-listener.en.md
  docs/content/user-manual/job-reconcile.en.md
  docs/content/user-manual/job-sharding-strategy.cn.md
  docs/content/user-manual/job-sharding-strategy.en.md
  docs/content/user-manual/operation-manual.en.md
  docs/content/user-manual/web-console.en.md
Labels: document

#994 #991, change favicon.ico for console
  elastic-job-lite-console/src/main/resources/console/favicon.ico
Labels: console

#995 #987, add download page
  docs/content/blog/_index.cn.md
  docs/content/blog/_index.en.md
  docs/content/downloads/_index.cn.md
  docs/content/downloads/_index.en.md
  docs/content/faq/_index.cn.md
  docs/content/faq/_index.en.md
  docs/content/powered-by/_index.cn.md
  docs/content/powered-by/_index.en.md
Labels: document

#997 Fix JobOperateAPIImpl#enable bug
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/operate/JobOperateAPIImpl.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/operate/JobOperateAPIImplTest.java
Labels: bug

#998 Update Elastic-Job to ElasticJob
  README.md
  README_ZH.md
  docs/content/faq/_index.cn.md
  docs/content/features/elastic.cn.md
  docs/content/overview/_index.cn.md
  docs/content/overview/_index.en.md
  docs/content/user-manual/_index.en.md
  docs/content/user-manual/job-api.cn.md
  docs/content/user-manual/job-reconcile.cn.md
  docs/content/user-manual/web-console.cn.md
  elastic-job-lite-console/README.md
  examples/README.md
Labels: document

#1000 Fix job can not enable for disabled job integrate test sometimes
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/BaseIntegrateTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/disable/ScheduleDisabledJobIntegrateTest.java
Labels: test

#1002 Update download page
  README_ZH.md
  docs/content/downloads/_index.cn.md
  docs/content/downloads/_index.en.md
  docs/content/overview/_index.cn.md
Labels: document

#1006 Update readme
  README.md
  README_ZH.md
Labels: document

#1007 Update features of readme
  README.md
  README_ZH.md
Labels: document

#1011 translate RELEASE-NOTES.md from Chinese to English
  RELEASE-NOTES.md
Labels: document

#1014 Test case `org.apache.shardingsphere.elasticjob.lite.integrate.enable…
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/election/ElectionListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/server/ServerNode.java
Labels: bug

#1017 #967, updata xmlns
  README.md
  README_ZH.md
  docs/content/quick-start/_index.cn.md
  docs/content/user-manual/dump.cn.md
  docs/content/user-manual/job-api.cn.md
  docs/content/user-manual/job-reconcile.cn.md
  elasticjob-lite/elasticjob-lite-spring/src/main/resources/META-INF/namespace/elasticjob.xsd
  elasticjob-lite/elasticjob-lite-spring/src/main/resources/META-INF/spring.handlers
  elasticjob-lite/elasticjob-lite-spring/src/main/resources/META-INF/spring.schemas
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/job/base.xml
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/job/withEventTraceRdb.xml
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/job/withJobHandler.xml
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/job/withJobRef.xml
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/job/withListener.xml
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/job/withListenerAndCglib.xml
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/job/withListenerAndJdkDynamicProxy.xml
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/job/withoutListener.xml
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/reg/regContext.xml
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/snapshot/snapshotDisabled.xml
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/snapshot/snapshotEnabled.xml
  examples/elasticjob-example-lite-spring/src/main/resources/META-INF/applicationContext.xml
Labels: spring

#1020 change base url to current
  docs/config.toml
  docs/content/dev-manual/lite-design.cn.md
  docs/content/overview/_index.cn.md
  docs/content/user-manual/dump.cn.md
  docs/layouts/index.html
  docs/layouts/partials/favicon.html
  docs/layouts/partials/logo.html
  docs/layouts/partials/style.html
Labels: document

#1021 Update readme.md
  README.md
  README_ZH.md
Labels: document

#1022 Use java 8 style for elasticjob cloud
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/context/TaskContext.java
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/reg/zookeeper/ZookeeperRegistryCenter.java
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/statistics/rdb/StatisticRdbRepository.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/fixture/EmbedTestingServer.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/statistics/rdb/StatisticRdbRepositoryTest.java
  elasticjob-cloud/elasticjob-cloud-executor/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/TaskExecutor.java
  elasticjob-cloud/elasticjob-cloud-executor/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/local/fixture/TestDataflowJob.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/restful/RestfulServer.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/env/BootstrapEnvironment.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/ha/FrameworkIDService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/AppConstraintEvaluator.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/FacadeService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/MesosStateService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/ReconcileService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/SchedulerService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/TaskLaunchScheduledService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/producer/ProducerManager.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudAppRestfulApi.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudJobRestfulApi.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/RestfulService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/failover/FailoverService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/ready/ReadyService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/running/RunningService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/StatisticManager.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/job/JobRunningStatisticJob.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/job/RegisteredJobStatisticJob.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/job/TaskResultStatisticJob.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/restful/RestfulServerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/restful/fixture/TestRestfulApi.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/env/BootstrapEnvironmentTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/fixture/EmbedTestingServer.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/ha/FrameworkIDServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/AppConstraintEvaluatorTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/FacadeServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/SchedulerEngineTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/TaskLaunchScheduledServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/producer/ProducerManagerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/AbstractCloudRestfulApiTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/failover/FailoverServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/ready/ReadyServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/StatisticManagerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/job/JobRunningStatisticJobTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/job/RegisteredJobStatisticJobTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/job/TaskResultStatisticJobTest.java
  examples/elasticjob-example-embed-zk/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/EmbedZookeeperServer.java
Labels: refactor

#1023 Use static import with test cases
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/api/ShardingContextTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/config/JobCoreConfigurationTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/context/TaskContextTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/exception/ExceptionUtilTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/exception/JobConfigurationExceptionTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/exception/JobExecutionEnvironmentExceptionTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/exception/JobSystemExceptionTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/JobExecutorFactoryTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/handler/ExecutorServiceHandlerRegistryTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/handler/JobPropertiesTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/reg/zookeeper/ZookeeperConfigurationTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/reg/zookeeper/ZookeeperRegistryCenterQueryWithoutCacheTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/statistics/rdb/StatisticRdbRepositoryTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/util/concurrent/ExecutorServiceObjectTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/util/digest/EncryptionTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/util/env/TimeServiceTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/util/json/JobConfigurationGsonTypeAdapterTest.java
  elasticjob-cloud/elasticjob-cloud-executor/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/CloudJobFacadeTest.java
  elasticjob-cloud/elasticjob-cloud-executor/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/JobConfigurationContextTest.java
  elasticjob-cloud/elasticjob-cloud-executor/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/TaskExecutorThreadTest.java
  elasticjob-cloud/elasticjob-cloud-executor/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/local/LocalTaskExecutorTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/restful/RestfulExceptionTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/restful/RestfulServerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationNodeTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationNodeTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/context/JobContextTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/env/BootstrapEnvironmentTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/ha/FrameworkIDServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/AppConstraintEvaluatorTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/FacadeServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/JobTaskRequestTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/LaunchingTasksTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/LeasesQueueTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/MesosStateServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/SchedulerEngineTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/SchedulerServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/TaskInfoDataTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudAppRestfulApiTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudJobRestfulApiTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudOperationRestfulApiTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/disable/app/DisableAppNodeTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/disable/app/DisableAppServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/disable/job/DisableJobNodeTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/disable/job/DisableJobServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/failover/FailoverNodeTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/failover/FailoverServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/ready/ReadyNodeTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/ready/ReadyServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/running/RunningNodeTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/running/RunningServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/StatisticManagerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/job/JobRunningStatisticJobTest.java
  elasticjob-common/elasticjob-tracing/elasticjob-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/tracing/JobEventBusTest.java
  elasticjob-common/elasticjob-tracing/elasticjob-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/tracing/rdb/listener/RDBTracingListenerTest.java
Labels: test

#1024 Use static import with CoreMatchers for test cases
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/exception/JobConfigurationExceptionTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/exception/JobSystemExceptionTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/JobExecutorFactoryTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/restful/RestfulExceptionTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/env/BootstrapEnvironmentTest.java
  elasticjob-common/elasticjob-tracing/elasticjob-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/tracing/event/JobExecutionEventTest.java
Labels: test

#1026 Simplify ShardingContext's constructor
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/api/ShardingContext.java
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/AbstractElasticJobExecutor.java
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/ShardingContexts.java
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/util/digest/Encryption.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/util/digest/EncryptionTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfiguration.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/job/ShardingContext.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutor.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ShardingContexts.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/job/ShardingContextTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/ShardingContextsTest.java
Labels: refactor

#1033 Refactor LocalTaskExecutor
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/JobFacade.java
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/handler/ExecutorServiceHandler.java
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/handler/ExecutorServiceHandlerRegistry.java
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/handler/JobExceptionHandler.java
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/handler/impl/DefaultExecutorServiceHandler.java
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/handler/impl/DefaultJobExceptionHandler.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/handler/ExecutorServiceHandlerRegistryTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/handler/impl/DefaultJobExceptionHandlerTest.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/handler/impl/JobEventCaller.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/resources/logback-test.xml
  elasticjob-cloud/elasticjob-cloud-executor/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/CloudJobFacade.java
  elasticjob-cloud/elasticjob-cloud-executor/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/DaemonTaskScheduler.java
  elasticjob-cloud/elasticjob-cloud-executor/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/JobTypeConfigurationUtil.java
  elasticjob-cloud/elasticjob-cloud-executor/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/local/LocalCloudJobConfiguration.java
  elasticjob-cloud/elasticjob-cloud-executor/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/local/LocalTaskExecutor.java
  elasticjob-cloud/elasticjob-cloud-executor/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/CloudJobFacadeTest.java
  elasticjob-cloud/elasticjob-cloud-executor/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/local/LocalTaskExecutorTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/AllCloudAppConfigTests.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/AllCloudJobConfigTests.java
  elasticjob-infra/elasticjob-infra-common/src/main/java/org/apache/shardingsphere/elasticjob/infra/handler/threadpool/impl/AbstractJobExecutorServiceHandler.java
  elasticjob-lite/elasticjob-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/util/HomeFolderUtils.java
  elasticjob-lite/elasticjob-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/util/HomeFolderUtilsTest.java
Labels: refactor

#1034 fix logo url
  docs/layouts/partials/favicon.html
Labels: document

#1046 Rename YamlJobConfiguration to JobConfigurationPOJO
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/config/pojo/CloudJobConfigurationPOJO.java
  elasticjob-cloud/elasticjob-cloud-common/src/test/java/org/apache/shardingsphere/elasticjob/cloud/config/pojo/CloudJobConfigurationPOJOTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationListener.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationService.java
  elasticjob-infra/elasticjob-tracing/elasticjob-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/tracing/rdb/storage/RDBJobEventStorage.java
  elasticjob-lite/elasticjob-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/JobConfigController.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationService.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/RescheduleListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/pojo/JobConfigurationPOJO.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/MonitorExecutionListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/disable/DisabledJobIntegrateTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/enable/EnabledJobIntegrateTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationServiceTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/pojo/JobConfigurationPOJOTest.java
  elasticjob-lite/elasticjob-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/api/JobConfigurationAPI.java
  elasticjob-lite/elasticjob-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobConfigurationAPIImpl.java
  elasticjob-lite/elasticjob-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/JobStatisticsAPIImpl.java
  elasticjob-lite/elasticjob-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobConfigurationAPIImplTest.java
Labels: refactor

#1049 Use YAML instead of JSON for app configuration persist
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/util/json/CloudJobConfigurationGsonFactory.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfiguration.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/pojo/CloudAppConfigurationPOJO.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/pojo/CloudAppConfigurationPOJOTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudAppRestfulApiTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/job/RegisteredJobStatisticJobTest.java
Labels: cloud, refactor

#1051 For code style
  elasticjob-cloud/elasticjob-cloud-executor/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/DaemonTaskScheduler.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/Bootstrap.java
Labels: refactor

#1054 Remove unitils dependency
  elasticjob-cloud/elasticjob-cloud-common/pom.xml
  elasticjob-cloud/elasticjob-cloud-executor/pom.xml
  elasticjob-cloud/elasticjob-cloud-executor/src/test/java/org/apache/shardingsphere/elasticjob/cloud/executor/TaskExecutorTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/pom.xml
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/ReflectionUtils.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationListenerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/env/BootstrapEnvironmentTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/FacadeServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/LaunchingTasksTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/SchedulerEngineTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/producer/ProducerManagerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/producer/TransientProducerSchedulerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudJobRestfulApiTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudOperationRestfulApiTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/failover/FailoverServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/ready/ReadyServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/StatisticManagerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/StatisticsSchedulerTest.java
  pom.xml
Labels: test

#1055 add maven wrapper support.
  .mvn/jvm.config
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: build, enhancement

#1057 Decouple some guava usage
  elasticjob-cloud/elasticjob-cloud-executor/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/local/LocalTaskExecutor.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/restful/RestfulServer.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/AppConstraintEvaluator.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/FacadeService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/MesosStateService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/TaskLaunchScheduledService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/producer/ProducerManager.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudAppRestfulApi.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/search/JobEventRdbSearch.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/failover/FailoverNode.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/failover/FailoverService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/failover/FailoverTaskInfo.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/running/RunningNode.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/running/RunningService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/security/WwwAuthFilter.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/fixture/EmbedTestingServer.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/fixture/TaskNode.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/AppConstraintEvaluatorTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/FacadeServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/MesosStateServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/TaskLaunchScheduledServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/producer/ProducerManagerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudAppRestfulApiTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudJobRestfulApiTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/failover/FailoverServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/ready/ReadyServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/running/RunningServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/StatisticManagerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/job/RegisteredJobStatisticJobTest.java
  elasticjob-infra/elasticjob-infra-common/src/main/java/org/apache/shardingsphere/elasticjob/infra/concurrent/ElasticJobExecutorService.java
  elasticjob-infra/elasticjob-infra-common/src/main/java/org/apache/shardingsphere/elasticjob/infra/context/TaskContext.java
  elasticjob-infra/elasticjob-infra-common/src/test/java/org/apache/shardingsphere/elasticjob/infra/context/TaskContextTest.java
  elasticjob-infra/elasticjob-infra-common/src/test/java/org/apache/shardingsphere/elasticjob/infra/context/fixture/TaskNode.java
  elasticjob-infra/elasticjob-registry-center/src/test/java/org/apache/shardingsphere/elasticjob/reg/zookeeper/fixture/EmbedTestingServer.java
  elasticjob-infra/elasticjob-tracing/elasticjob-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/tracing/JobEventBus.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeNode.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionContextService.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SnapshotService.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/util/SensitiveInfoUtils.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/EmbedTestingServer.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacadeTest.java
  elasticjob-lite/elasticjob-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/AbstractEmbedZookeeperBaseTest.java
Labels: refactor

#1060 Upgrade guava and curator version to newest
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationListener.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/failover/FailoverService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationListenerTest.java
  elasticjob-infra/elasticjob-registry-center/src/main/java/org/apache/shardingsphere/elasticjob/reg/zookeeper/ZookeeperRegistryCenter.java
  elasticjob-infra/elasticjob-registry-center/src/test/java/org/apache/shardingsphere/elasticjob/reg/zookeeper/ZookeeperElectionServiceTest.java
  elasticjob-infra/elasticjob-registry-center/src/test/java/org/apache/shardingsphere/elasticjob/reg/zookeeper/ZookeeperRegistryCenterMiscellaneousTest.java
  elasticjob-lite/elasticjob-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/domain/EventTraceDataSourceFactory.java
  elasticjob-lite/elasticjob-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/security/UserAuthenticationService.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/RescheduleListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/election/ElectionListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/ShutdownListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/TriggerListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/listener/AbstractJobListener.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/listener/AbstractListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/MonitorExecutionListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingService.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SnapshotService.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/storage/JobNodeStorage.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/storage/TransactionExecutionCallback.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/RescheduleListenerManagerTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/election/ElectionListenerManagerTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManagerTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeListenerManagerTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/ShutdownListenerManagerTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/TriggerListenerManagerTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/listener/JobListenerTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/listener/fixture/FooJobListener.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/MonitorExecutionListenerManagerTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingListenerManagerTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingServiceTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/storage/JobNodeStorageTest.java
  elasticjob-lite/elasticjob-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/reg/RegistryCenterFactory.java
  examples/pom.xml
  pom.xml
Labels: refactor

#1061 Update required ZooKeeper version
  docs/content/faq/_index.cn.md
  docs/content/user-manual/job-api.cn.md
Labels: document

#1065 Add setDestroyMethodName for reg spring namespace
  elasticjob-lite/elasticjob-lite-spring-boot-starter/src/main/java/org/apache/shardingsphere/elasticjob/lite/boot/ElasticJobLiteAutoConfiguration.java
  elasticjob-lite/elasticjob-lite-spring-boot-starter/src/main/java/org/apache/shardingsphere/elasticjob/lite/boot/ElasticJobStartupRunner.java
  elasticjob-lite/elasticjob-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/reg/parser/ZookeeperBeanDefinitionParser.java
Labels: enhancement, lite, spring

#1063 Fix bootstrap class in the start script
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/resources/bin/dcos.sh
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/resources/bin/start.sh
Labels: bug, cloud

#1064 Expected error message should hide in logback-test.xml
  elasticjob-lite/elasticjob-lite-core/src/test/resources/logback-test.xml
Labels: test

#1066 Update quick start
  docs/content/quick-start/_index.cn.md
  docs/content/quick-start/_index.en.md
  docs/content/quick-start/elasticjob-cloud.cn.md
  docs/content/quick-start/elasticjob-cloud.en.md
  docs/content/quick-start/elasticjob-lite.cn.md
  docs/content/quick-start/elasticjob-lite.en.md
Labels: document

#1068 Update overview
  README.md
  README_ZH.md
  docs/content/dev-manual/lite-design.cn.md
  docs/content/overview/_index.cn.md
  docs/content/overview/_index.en.md
  docs/content/user-manual/dump.cn.md
  docs/layouts/partials/logo.html
  docs/static/img/architecture/elasticjob_cloud.png
  docs/static/img/architecture/elasticjob_lite.png
  docs/static/img/elasticjob.png
Labels: document

#1070 Add resource assign to feature
  docs/content/features/failover.cn.md
  docs/content/features/failover.en.md
  docs/content/features/jobt-ype.cn.md
  docs/content/features/misfired.cn.md
  docs/content/features/misfired.en.md
  docs/content/features/resource.cn.md
  docs/content/features/resource.en.md
Labels: document

#1072 Update download
  docs/content/downloads/_index.cn.md
  docs/content/downloads/_index.en.md
Labels: document

#1073 Update FAQ
  docs/content/faq/_index.cn.md
Labels: document

#1074 Update github link
  README.md
  README_ZH.md
  docs/content/overview/_index.cn.md
  docs/content/overview/_index.en.md
  docs/content/powered-by/_index.cn.md
  pom.xml
Labels: document

#1075 Update ElasticJob Lite & ElasticJob Cloud to ElasticJob-Lite & ElasticJob-Cloud
  README.md
  README_ZH.md
  ROADMAP.md
  docs/content/dev-manual/roadmap.cn.md
  docs/content/dev-manual/roadmap.en.md
  docs/content/downloads/_index.en.md
  docs/content/faq/_index.cn.md
  docs/content/features/elastic.cn.md
  docs/content/features/resource.cn.md
  docs/content/overview/_index.cn.md
  docs/content/overview/_index.en.md
  docs/content/quick-start/elasticjob-cloud.cn.md
  docs/content/quick-start/elasticjob-cloud.en.md
  docs/content/quick-start/elasticjob-lite.cn.md
  docs/content/quick-start/elasticjob-lite.en.md
  docs/content/user-manual/elasticjob-lite/deploy-guide.cn.md
  docs/content/user-manual/elasticjob-lite/dump.cn.md
  docs/content/user-manual/elasticjob-lite/event-trace.cn.md
  docs/content/user-manual/elasticjob-lite/execution-monitor.cn.md
  docs/content/user-manual/elasticjob-lite/job-api.cn.md
  docs/content/user-manual/elasticjob-lite/web-console.cn.md
  elasticjob-cloud/elasticjob-cloud-executor/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/TaskExecutor.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/resources/conf/elasticjob-cloud-scheduler.properties
  elasticjob-lite/elasticjob-lite-console/README.md
  elasticjob-lite/elasticjob-lite-spring-boot-starter/README.md
  examples/elasticjob-example-cloud/src/README.txt
Labels: document

#1077 Use Guava Strings class instead of assertj Strings class
  elasticjob-lite/elasticjob-lite-spring-boot-starter/src/main/java/org/apache/shardingsphere/elasticjob/lite/boot/ElasticJobLiteAutoConfiguration.java
Labels: refactor

#1079 Add elasticjob-distribution module
  elasticjob-distribution/elasticjob-cloud-distribution/pom.xml
  elasticjob-distribution/elasticjob-cloud-distribution/src/main/assembly/elasticjob-cloud-binary-distribution.xml
  elasticjob-distribution/elasticjob-cloud-distribution/src/main/release-docs/README.txt
  elasticjob-distribution/elasticjob-lite-distribution/pom.xml
  elasticjob-distribution/elasticjob-lite-distribution/src/main/assembly/elasticjob-lite-binary-distribution.xml
  elasticjob-distribution/elasticjob-lite-distribution/src/main/release-docs/README.txt
  elasticjob-distribution/elasticjob-src-distribution/pom.xml
  elasticjob-distribution/elasticjob-src-distribution/src/main/assembly/source-distribution.xml
  elasticjob-distribution/pom.xml
  pom.xml
Labels: release

#1080 Use String.join instead of StringJoiner and Collectors.joining
  docs/static/img/license.svg
  elasticjob-cloud/elasticjob-cloud-executor/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/local/LocalTaskExecutor.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/restful/RestfulServer.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/TaskLaunchScheduledService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/security/WwwAuthFilter.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/fixture/TaskNode.java
  elasticjob-infra/elasticjob-infra-common/src/main/java/org/apache/shardingsphere/elasticjob/infra/concurrent/ElasticJobExecutorService.java
  elasticjob-infra/elasticjob-infra-common/src/main/java/org/apache/shardingsphere/elasticjob/infra/context/TaskContext.java
  elasticjob-infra/elasticjob-infra-common/src/test/java/org/apache/shardingsphere/elasticjob/infra/context/fixture/TaskNode.java
  elasticjob-infra/elasticjob-tracing/elasticjob-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/tracing/JobEventBus.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeNode.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionContextService.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SnapshotService.java
Labels: refactor

#1069 Consider about improvement of get IP address inaccurate
  elasticjob-infra/elasticjob-infra-common/src/main/java/org/apache/shardingsphere/elasticjob/infra/env/HostException.java
  elasticjob-infra/elasticjob-infra-common/src/main/java/org/apache/shardingsphere/elasticjob/infra/env/IpUtils.java
Labels: enhancement, kernel

#1082 CloudJobConfigurationPOJO instead of CloudJobConfiguration
  elasticjob-cloud/elasticjob-cloud-common/src/main/java/org/apache/shardingsphere/elasticjob/cloud/util/json/JobConfigurationGsonTypeAdapter.java
  elasticjob-cloud/elasticjob-cloud-scheduler/pom.xml
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationListener.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/env/BootstrapEnvironment.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/AppConstraintEvaluator.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/FacadeService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/TaskLaunchScheduledService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/producer/ProducerManager.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/producer/TransientProducerScheduler.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudAppRestfulApi.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudJobRestfulApi.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/failover/FailoverService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/ready/ReadyService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/running/RunningService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/statistics/StatisticManager.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/context/JobContextTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/fixture/CloudJobConfigurationBuilder.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/fixture/CloudJsonConstants.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/FacadeServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/JobTaskRequestTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/LaunchingTasksTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/TaskInfoDataTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/TaskLaunchScheduledServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/producer/ProducerManagerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/producer/TransientProducerSchedulerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudJobRestfulApiTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/ready/ReadyServiceTest.java
Labels: cloud, refactor

#1084 Use CloudAppConfigurationPOJO instead of CloudAppConfiguration
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationGsonFactory.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/AppConstraintEvaluator.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/FacadeService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/TaskLaunchScheduledService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/producer/ProducerManager.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/restful/CloudAppRestfulApi.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/fixture/CloudAppConfigurationBuilder.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/FacadeServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/producer/ProducerManagerTest.java
Labels: cloud, refactor

#1089 Add comparison table on readme
  README.md
  README_ZH.md
  docs/content/overview/_index.cn.md
  docs/content/overview/_index.en.md
Labels: document

#1088 Support annotate @Transactional for job class (##472)
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobScheduler.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/util/ProxyUtils.java
Labels: bug, spring

#1090 Revert #1088
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobScheduler.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/util/ProxyUtils.java
Labels: spring

#1091 Update overview and quick-start
  README.md
  README_ZH.md
  docs/content/overview/_index.cn.md
  docs/content/overview/_index.en.md
  docs/content/quick-start/elasticjob-cloud.cn.md
  docs/content/quick-start/elasticjob-cloud.en.md
  docs/content/quick-start/elasticjob-lite.cn.md
  docs/content/quick-start/elasticjob-lite.en.md
  elasticjob-lite/elasticjob-lite-spring-boot-starter/src/main/java/org/apache/shardingsphere/elasticjob/lite/boot/ElasticJobLiteAutoConfiguration.java
Labels: document

#1092 Polish readme
  README.md
  README_ZH.md
  docs/content/features/elastic.en.md
  docs/content/overview/_index.cn.md
  docs/content/overview/_index.en.md
Labels: document

#1094 Update powered-by
  docs/content/powered-by/_index.cn.md
Labels: document

#1095 Update powered-by en
  docs/content/powered-by/_index.en.md
Labels: document

#1099 Add schedule model and update elastic page
  docs/content/dev-manual/lite-design.cn.md
  docs/content/features/elastic.cn.md
  docs/content/features/elastic.en.md
  docs/content/features/failover.cn.md
  docs/content/features/failover.en.md
  docs/content/features/jobt-ype.cn.md
  docs/content/features/jobt-ype.en.md
  docs/content/features/misfired.cn.md
  docs/content/features/misfired.en.md
  docs/content/features/resource.cn.md
  docs/content/features/resource.en.md
  docs/content/features/schedule-model.cn.md
  docs/content/features/schedule-model.en.md
  docs/static/img/elastic/ha.png
  docs/static/img/elastic/sacle-out.png
  docs/static/img/elastic/sharding.png
Labels: document

#1100 fix link in docs
  .gitignore
  docs/config.toml
Labels: document

#1102 Update failover page
  docs/content/features/elastic.cn.md
  docs/content/features/failover.cn.md
  docs/static/img/failover/job-crash.png
  docs/static/img/failover/job-failover.png
  docs/static/img/failover/job.png
Labels: document

#1103 Update Misfire page
  docs/content/features/misfire.cn.md
  docs/content/features/misfire.en.md
  docs/content/features/misfired.cn.md
  docs/static/img/misfire/job-misfire.png
  docs/static/img/misfire/job-missed.png
  docs/static/img/misfire/job.png
Labels: document

#1104 Update job type page
  docs/content/features/jobt-ype.cn.md
Labels: document

#1108 Update index of lite and cloud user-manual
  docs/content/user-manual/elasticjob-cloud/_index.cn.md
  docs/content/user-manual/elasticjob-cloud/_index.en.md
  docs/content/user-manual/elasticjob-lite/_index.cn.md
  docs/content/user-manual/elasticjob-lite/_index.en.md
Labels: document

#1107 Translate docs/content/features/schedule-model.en.md
  docs/content/features/schedule-model.en.md
Labels: document

#1109 Update index of usage
  docs/content/user-manual/elasticjob-cloud/usage/_index.cn.md
  docs/content/user-manual/elasticjob-cloud/usage/_index.en.md
  docs/content/user-manual/elasticjob-lite/usage/_index.cn.md
  docs/content/user-manual/elasticjob-lite/usage/_index.en.md
Labels: document

#1111 Add document for set IP address by environment variable
  docs/content/faq/_index.cn.md
  docs/content/features/job-type.cn.md
  docs/content/features/job-type.en.md
Labels: document

#1112 Update document of job api
  README.md
  README_ZH.md
  docs/content/overview/_index.cn.md
  docs/content/overview/_index.en.md
  docs/content/user-manual/elasticjob-cloud/usage/_index.cn.md
  docs/content/user-manual/elasticjob-lite/usage/_index.cn.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/_index.cn.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/_index.en.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/event-trace.cn.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/event-trace.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/_index.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/_index.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/java-api.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/java-api.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/job-interface.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/job-interface.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-boot-starter.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-boot-starter.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-namespace.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-namespace.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/_index.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/_index.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/job-listener.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/job-listener.en.md
  docs/content/user-manual/elasticjob-lite/usage/operation-api/_index.cn.md
  docs/content/user-manual/elasticjob-lite/usage/operation-api/_index.en.md
  docs/content/user-manual/elasticjob-lite/usage/operation-api/operation-api.cn.md
  docs/content/user-manual/elasticjob-lite/usage/operation-api/operation-api.en.md
Labels: document

#1106 Add job identification strategy. (#472)
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobScheduler.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/JobClassNameProvider.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/JobClassNameProviderFactory.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/SimpleJobClassNameProvider.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/JobClassNameProviderFactoryTest.java
  elasticjob-lite/elasticjob-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/setup/SpringProxyJobClassNameProvider.java
  elasticjob-lite/elasticjob-lite-spring/src/main/resources/META-INF/services/org.apache.shardingsphere.elasticjob.lite.internal.setup.JobClassNameProvider
  elasticjob-lite/elasticjob-lite-spring/src/test/java/org/apache/shardingsphere/elasticjob/lite/spring/setup/JobClassNameProviderFactoryTest.java
Labels: bug, kernel

#1120 Translate user manual, spring namespace for job-api.
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-namespace.en.md
Labels: document

#1122 Revise #1106
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/JobClassNameProviderFactory.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/SimpleJobClassNameProvider.java
  elasticjob-lite/elasticjob-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/setup/SpringProxyJobClassNameProvider.java
Labels: refactor

#1123 Revise #1120
  docs/content/features/schedule-model.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-namespace.en.md
Labels: document

#1121 Translate docs/content/user-manual/elasticjob-lite/usage/job-api/spring-boot-starter.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-boot-starter.en.md
Labels: document

#1101 Translate powered-by page
  docs/content/powered-by/_index.en.md
Labels: document

#1124 Revise #1101
  docs/content/powered-by/_index.en.md
Labels: document

#1125 Translate failover.en.md & misfire.en.md
  docs/content/features/failover.en.md
  docs/content/features/misfire.en.md
Labels: document

#1126 Translate java-api.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/java-api.en.md
Labels: document

#1127 translate user manual, job-interface for job-api.
  docs/content/user-manual/elasticjob-lite/usage/job-api/job-interface.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-namespace.en.md
Labels: document

#1134 Update event-trace doc
  docs/content/user-manual/elasticjob-lite/usage/event-trace/_index.cn.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/event-trace.cn.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/java-api.cn.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/java-api.en.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/spring-boot-starter.cn.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/spring-boot-starter.en.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/spring-namespace.cn.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/spring-namespace.en.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/table-structure.cn.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/table-structure.en.md
Labels: document

#1135 For #1131 Translate index & listener-interface
  docs/content/user-manual/elasticjob-lite/usage/job-listener/_index.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/listener-interface.en.md
Labels: document

#1136 Remove job-listener/spring-boot-starter page
  docs/content/user-manual/elasticjob-lite/usage/job-listener/spring-boot-starter.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/spring-boot-starter.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/spring-namespace.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/spring-namespace.en.md
Labels: document

#1140 Update document of operation-api
  docs/content/user-manual/elasticjob-lite/usage/operation-api/_index.cn.md
  docs/content/user-manual/elasticjob-lite/usage/operation-api/operation-api.cn.md
  docs/content/user-manual/elasticjob-lite/usage/operation-api/operation-api.en.md
Labels: document

#1139 Translate user manual, index for event-trace.
  docs/content/user-manual/elasticjob-lite/usage/event-trace/_index.en.md
Labels: document

#1144 Translate user manual, java-api and spring-namespace for event-trace.
  docs/content/user-manual/elasticjob-lite/usage/event-trace/java-api.en.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/spring-namespace.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-namespace.en.md
Labels: document

#1145 Translate resource.en.md
  docs/content/features/resource.en.md
Labels: document

#1141 Support job-type configuration of spring namespace #1114
  elasticjob-lite/elasticjob-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/JobBeanDefinitionParser.java
  elasticjob-lite/elasticjob-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/tag/JobBeanDefinitionTag.java
  elasticjob-lite/elasticjob-lite-spring/src/main/resources/META-INF/namespace/elasticjob.xsd
  elasticjob-lite/elasticjob-lite-spring/src/test/java/org/apache/shardingsphere/elasticjob/lite/spring/job/JobSpringNamespaceWithTypeTest.java
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/job/withJobType.xml
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/conf/job/conf.properties
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/script/demo.bat
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/script/demo.sh
Labels: spring

#1147 Remove execution of OneOff job when Spring Boot Application started
  elasticjob-lite/elasticjob-lite-spring-boot-starter/src/main/java/org/apache/shardingsphere/elasticjob/lite/boot/ElasticJobStartupRunner.java
Labels: spring

#1148 Translate docs/content/features/elastic.en.md
  docs/content/features/elastic.en.md
Labels: document

#1155 Update configuration index
  docs/content/user-manual/elasticjob-lite/configuration/_index.cn.md
  docs/content/user-manual/elasticjob-lite/operation/_index.cn.md
  docs/content/user-manual/elasticjob-lite/operation/_index.en.md
Labels: document

#1154 Translate user manual, table-structure for event-trace.
  docs/content/user-manual/elasticjob-lite/usage/event-trace/table-structure.en.md
Labels: document

#1156 change console authorization encode from sha256 to md5
  elasticjob-lite/elasticjob-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/security/UserAuthenticationService.java
Labels: console

#1157 Add document for set IP address by environment variable
  docs/content/faq/_index.cn.md
  docs/content/user-manual/elasticjob-lite/operation/deploy-guide.cn.md
  docs/content/user-manual/elasticjob-lite/operation/execution-monitor.cn.md
  docs/content/user-manual/elasticjob-lite/operation/execution-monitor.en.md
  docs/content/user-manual/elasticjob-lite/operation/job-reconcile.cn.md
  docs/content/user-manual/elasticjob-lite/operation/job-reconcile.en.md
  docs/content/user-manual/elasticjob-lite/operation/web-console.cn.md
  docs/content/user-manual/elasticjob-lite/operation/web-console.en.md
Labels: document

#1158 Add document for usage of snapshot service
  docs/content/user-manual/elasticjob-lite/operation/dump.cn.md
  docs/content/user-manual/elasticjob-lite/operation/dump.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/java-api.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/java-api.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-namespace.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-namespace.en.md
Labels: document

#1159 Update dump for operation
  docs/content/user-manual/elasticjob-lite/operation/dump.cn.md
  docs/content/user-manual/elasticjob-lite/operation/dump.en.md
Labels: document

#1160 Update web-console for operation
  docs/content/user-manual/elasticjob-lite/operation/web-console.cn.md
Labels: document

#1166 Move lite-design to elastic doc
  docs/content/dev-manual/lite-design.cn.md
  docs/content/dev-manual/lite-design.en.md
  docs/content/features/elastic.cn.md
Labels: document

#1162 Add event trace spring boot starter usage document
  docs/content/user-manual/elasticjob-lite/usage/event-trace/spring-boot-starter.cn.md
  docs/content/user-manual/elasticjob-lite/usage/event-trace/spring-boot-starter.en.md
Labels: document

#1163 Consider about cannot permit port as -1 for disable SnapshotService #1152
  docs/content/user-manual/elasticjob-lite/configuration/spring-namespace.cn.md
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SnapshotService.java
  elasticjob-lite/elasticjob-lite-spring/src/main/resources/META-INF/namespace/elasticjob.xsd
  elasticjob-lite/elasticjob-lite-spring/src/test/resources/META-INF/snapshot/snapshotDisabled.xml
Labels: enhancement, lite

#1164 Update example for spring boot starter
  examples/elasticjob-example-lite-springboot/pom.xml
  examples/elasticjob-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/controller/OneOffJobController.java
  examples/elasticjob-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/job/SpringBootDataflowJob.java
  examples/elasticjob-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/job/SpringBootSimpleJob.java
  examples/elasticjob-example-lite-springboot/src/main/resources/application.yml
Labels: example, spring

#1165 Translate user-manual\elasticjob-lite\operation-api to English
  docs/content/user-manual/elasticjob-lite/configuration/java-api.en.md
Labels: document

#1167 Translate user manual, index for configuration.
  docs/content/user-manual/elasticjob-lite/configuration/_index.en.md
Labels: document

#1175 Update user-manual/cloud/usage
  docs/content/user-manual/elasticjob-cloud/usage/dev-guide.cn.md
  docs/content/user-manual/elasticjob-cloud/usage/local-executor.cn.md
Labels: document

#1172 Translate user manual, spring-namespace for configuration.
  docs/content/user-manual/elasticjob-lite/configuration/spring-namespace.en.md
Labels: document
