Repository apache/shardingsphere-elasticjob, pull requests merged in 2020-09, with the labels that each got.

#1455 add editURL for docs
  docs/config.toml
Labels: document

#1472 Only leader can set resharding flag
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/reconcile/ReconcileService.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/SetUpFacade.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingService.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/reconcile/ReconcileServiceTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/SetUpFacadeTest.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingServiceTest.java
Labels: bug, kernel

#1478 Add download button by Cayman.
  docs/themes/hugo-theme-learn/layouts/partials/menu.html
Labels: document

#1481 Add EmailJobErrorHandler to support sending email when job error
  elasticjob-error-handler/elasticjob-error-handler-email/pom.xml
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/ConfigurationLoader.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailConfiguration.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandler.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/resources/META-INF/services/org.apache.shardingsphere.elasticjob.error.handler.JobErrorHandler
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/resources/error-handler-email.yaml
  elasticjob-error-handler/elasticjob-error-handler-email/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandlerTest.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/test/resources/error-handler-email.yaml
  elasticjob-infra/elasticjob-infra-common/src/main/java/org/apache/shardingsphere/elasticjob/infra/yaml/YamlEngine.java
  elasticjob-infra/elasticjob-infra-common/src/test/java/org/apache/shardingsphere/elasticjob/infra/yaml/YamlEngineTest.java
  elasticjob-infra/elasticjob-infra-common/src/test/resources/yaml-test.yaml
Labels: new feature

#1483 Narrow the scope of spring dependency management
  elasticjob-cloud/elasticjob-cloud-executor/pom.xml
  elasticjob-distribution/elasticjob-cloud-scheduler-distribution/pom.xml
  elasticjob-lite/elasticjob-lite-spring/pom.xml
  pom.xml
Labels: build, enhancement

#1490 update for dingtalk module
  docs/content/dev-manual/error-handler.cn.md
  docs/content/dev-manual/error-handler.en.md
  elasticjob-error-handler/elasticjob-error-handler-dingtalk/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/dingtalk/DingtalkConfiguration.java
  elasticjob-error-handler/elasticjob-error-handler-dingtalk/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/dingtalk/DingtalkJobErrorHandler.java
  elasticjob-error-handler/elasticjob-error-handler-dingtalk/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/env/DingtalkEnvironment.java
  elasticjob-error-handler/elasticjob-error-handler-dingtalk/src/main/resources/META-INF/services/org.apache.shardingsphere.elasticjob.error.handler.JobErrorHandler
  elasticjob-error-handler/elasticjob-error-handler-dingtalk/src/main/resources/conf/error-handler-dingtalk.yaml
  elasticjob-error-handler/elasticjob-error-handler-dingtalk/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/dingtalk/DingtalkJobErrorHandlerTest.java
  elasticjob-error-handler/elasticjob-error-handler-dingtalk/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/dingtalk/fixture/DingtalkInternalController.java
  elasticjob-error-handler/elasticjob-error-handler-dingtalk/src/test/resources/conf/error-handler-dingtalk.yaml
  examples/elasticjob-example-lite-java/src/main/resources/conf/error-handler-dingtalk.yaml
Labels: document, enhancement

#1488 Correct configuration of elasticjob-cloud-scheduler-distribution
  elasticjob-cloud/elasticjob-cloud-scheduler/pom.xml
  elasticjob-distribution/elasticjob-cloud-scheduler-distribution/pom.xml
  elasticjob-distribution/elasticjob-cloud-scheduler-distribution/src/main/assembly/elasticjob-cloud-scheduler-binary-distribution.xml
  elasticjob-distribution/elasticjob-cloud-scheduler-distribution/src/main/resources/application.properties
Labels: cloud, dependencies

#1495 Update doc for adding wechat error handler
  docs/content/dev-manual/error-handler.cn.md
  docs/content/dev-manual/error-handler.en.md
  examples/elasticjob-example-lite-java/src/main/resources/conf/error-handler-wechat.yaml
Labels: document, lite

#1489 Update doc as jobListener move to JobConfiguration
  docs/content/user-manual/elasticjob-lite/configuration/java-api.cn.md
  docs/content/user-manual/elasticjob-lite/configuration/java-api.en.md
  docs/content/user-manual/elasticjob-lite/configuration/spring-boot-starter.cn.md
  docs/content/user-manual/elasticjob-lite/configuration/spring-boot-starter.en.md
  docs/content/user-manual/elasticjob-lite/configuration/spring-namespace.cn.md
  docs/content/user-manual/elasticjob-lite/configuration/spring-namespace.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/java-api.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/java-api.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/listener-interface.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/listener-interface.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/spring-namespace.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-listener/spring-namespace.en.md
  elasticjob-infra/elasticjob-infra-common/src/main/resources/META-INF/services/org.apache.shardingsphere.elasticjob.infra.listener.ElasticJobListener
  examples/elasticjob-example-lite-spring/src/main/resources/conf/job.properties
Labels: document, example

#1500 Support system properties as config for email error handler and updat…
  docs/content/dev-manual/error-handler.cn.md
  docs/content/dev-manual/error-handler.en.md
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/ConfigurationLoader.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandler.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/resources/conf/error-handler-email.yaml
  elasticjob-error-handler/elasticjob-error-handler-email/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandlerTest.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/test/resources/conf/error-handler-email.yaml
  examples/elasticjob-example-lite-java/src/main/resources/conf/error-handler-email.yaml
Labels: document, enhancement

#1507 Add support for SSL and debug in email error handler
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/ConfigurationLoader.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailConfiguration.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandler.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/resources/conf/error-handler-email.yaml
  elasticjob-error-handler/elasticjob-error-handler-email/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandlerTest.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/test/resources/conf/error-handler-email.yaml
Labels: enhancement, lite

#1511 Code style for elasticjob-error-handler-email
  elasticjob-error-handler/elasticjob-error-handler-email/pom.xml
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailConfigurationLoader.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandler.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandlerTest.java
  pom.xml
Labels: refactor

#1512 Remove system env load for email configuration
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailConfigurationLoader.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandler.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandlerTest.java
Labels: refactor

#1513 Refactor EmailJobErrorHandler
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandler.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandlerTest.java
Labels: refactor

#1514 Init email session in constructor
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandler.java
  elasticjob-error-handler/elasticjob-error-handler-email/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandlerTest.java
Labels: refactor

#1518 Replace static method usage in email error handler
  elasticjob-error-handler/elasticjob-error-handler-email/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/email/EmailJobErrorHandler.java
Labels: enhancement

#1522 Move elasticjob-error-handler-general to general package
  elasticjob-error-handler/elasticjob-error-handler-impl/elasticjob-error-handler-general/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/general/IgnoreJobErrorHandler.java
  elasticjob-error-handler/elasticjob-error-handler-impl/elasticjob-error-handler-general/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/general/LogJobErrorHandler.java
  elasticjob-error-handler/elasticjob-error-handler-impl/elasticjob-error-handler-general/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/general/ThrowJobErrorHandler.java
  elasticjob-error-handler/elasticjob-error-handler-impl/elasticjob-error-handler-general/src/main/resources/META-INF/services/org.apache.shardingsphere.elasticjob.error.handler.JobErrorHandler
  elasticjob-error-handler/elasticjob-error-handler-impl/elasticjob-error-handler-general/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/JobErrorHandlerFactoryTest.java
  elasticjob-error-handler/elasticjob-error-handler-impl/elasticjob-error-handler-general/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/general/IgnoreJobErrorHandlerTest.java
  elasticjob-error-handler/elasticjob-error-handler-impl/elasticjob-error-handler-general/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/general/LogJobErrorHandlerTest.java
  elasticjob-error-handler/elasticjob-error-handler-impl/elasticjob-error-handler-general/src/test/java/org/apache/shardingsphere/elasticjob/error/handler/general/ThrowJobErrorHandlerTest.java
Labels: refactor
