Repository apache/shardingsphere-elasticjob, pull requests merged in 2020-08, with the labels that each got.

#1313 add docker profile
  elasticjob-distribution/elasticjob-cloud-scheduler-distribution/Dockerfile
  elasticjob-distribution/elasticjob-cloud-scheduler-distribution/pom.xml
Labels: release

#1318 Rename remain dangdang.com to apache.org
  examples/elasticjob-example-cloud/src/README.txt
  examples/elasticjob-example-cloud/src/main/java/org/apache/shardingsphere/elasticjob/cloud/example/CloudJobMain.java
  examples/elasticjob-example-cloud/src/main/resources/META-INF/applicationContext.xml
  examples/elasticjob-example-cloud/src/main/resources/bin/start.sh
Labels: licenses

#1320 Revise code style
  examples/elasticjob-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/controller/OneOffJobController.java
  examples/elasticjob-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/entity/Foo.java
  examples/elasticjob-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/job/SpringBootDataflowJob.java
  examples/elasticjob-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/job/SpringBootSimpleJob.java
  examples/elasticjob-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/repository/FooRepository.java
Labels: refactor

#1321 Add cloud app configuration & dissable listener
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationListener.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/SchedulerService.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/disable/app/CloudAppDisableListener.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationListenerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/mesos/SchedulerServiceTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/disable/app/CloudAppDisableListenerTest.java
Labels: cloud

#1324 Update release notes
  RELEASE-NOTES.md
Labels: document

#1325 Fixes delete listener event path
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationListener.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationListener.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/disable/app/CloudAppDisableListener.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/main/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/disable/job/CloudJobDisableListener.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/app/CloudAppConfigurationListenerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/config/job/CloudJobConfigurationListenerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/disable/app/CloudAppDisableListenerTest.java
  elasticjob-cloud/elasticjob-cloud-scheduler/src/test/java/org/apache/shardingsphere/elasticjob/cloud/scheduler/state/disable/job/CloudJobDisableListenerTest.java
Labels: cloud

#1329 修复哈希表初始容量以避免发生扩容
  elasticjob-infra/elasticjob-infra-common/src/main/java/org/apache/shardingsphere/elasticjob/infra/handler/sharding/impl/AverageAllocationJobShardingStrategy.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionContextService.java
Labels: enhancement, kernel

#1331 Improve Spring Boot OneOffJobBootstrap injection
  docs/content/user-manual/elasticjob-lite/configuration/spring-boot-starter.cn.md
  docs/content/user-manual/elasticjob-lite/configuration/spring-boot-starter.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-boot-starter.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-boot-starter.en.md
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/boot/job/ElasticJobConfigurationProperties.java
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/boot/job/ElasticJobLiteAutoConfiguration.java
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/test/java/org/apache/shardingsphere/elasticjob/lite/spring/boot/job/ElasticJobSpringBootTest.java
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/test/resources/application-elasticjob.yml
  examples/elasticjob-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/controller/OneOffJobController.java
  examples/elasticjob-example-lite-springboot/src/main/resources/application.yml
Labels: API, spring

#1334 Update pom format
  pom.xml
Labels: refactor

#1336 Update doc for the relationship of failover and execution monitor
  docs/content/features/failover.cn.md
  docs/content/features/failover.en.md
  docs/content/user-manual/elasticjob-lite/configuration/_index.cn.md
  docs/content/user-manual/elasticjob-lite/configuration/_index.en.md
Labels: document

#1341 Update release notes
  RELEASE-NOTES.md
Labels: document

#1346 Update download link
  docs/content/downloads/_index.cn.md
  docs/content/downloads/_index.en.md
Labels: document

#1347 Update readme for grammar problem
  README.md
  docs/content/overview/_index.en.md
  elasticjob-distribution/elasticjob-cloud-executor-distribution/src/main/release-docs/README.txt
  elasticjob-distribution/elasticjob-cloud-scheduler-distribution/src/main/release-docs/README.txt
  elasticjob-distribution/elasticjob-lite-distribution/src/main/release-docs/README.txt
Labels: document

#1348 Update document sites by Cayman
  docs/config.toml
  docs/content/downloads/_index.cn.md
  docs/content/downloads/_index.en.md
  docs/layouts/shortcodes/bilibili.html
  docs/static/css/theme-black.css
  docs/static/img/elasticjob.png
  docs/themes/hugo-theme-learn/layouts/partials/header.html
  docs/themes/hugo-theme-learn/static/css/hugo-theme.css
  docs/themes/hugo-theme-learn/static/css/hybrid.css
  docs/themes/hugo-theme-learn/static/css/nucleus.css
  docs/themes/hugo-theme-learn/static/css/theme.css
Labels: document

#1351 Update download page
  docs/content/downloads/_index.cn.md
  docs/content/downloads/_index.en.md
Labels: document

#1353 update company list
  docs/content/powered-by/_index.cn.md
  docs/content/powered-by/_index.en.md
Labels: document

#1354 Dependency is duplicated in file(s): elasticjob-executor-type
  elasticjob-executor/elasticjob-executor-type/elasticjob-dataflow-executor/pom.xml
  elasticjob-executor/elasticjob-executor-type/elasticjob-script-executor/pom.xml
  elasticjob-executor/elasticjob-executor-type/elasticjob-simple-executor/pom.xml
Labels: build

#1362 Update examples module version from 3.0.0-alpha-SNAPSHOT to 3.0.0-beta-SNAPSHOT
  examples/elasticjob-example-cloud/pom.xml
  examples/elasticjob-example-embed-zk/pom.xml
  examples/elasticjob-example-jobs/pom.xml
  examples/elasticjob-example-lite-java/pom.xml
  examples/elasticjob-example-lite-spring/pom.xml
  examples/elasticjob-example-lite-springboot/pom.xml
  examples/pom.xml
Labels: example

#1364 Fix JavaMain lacks import of HttpJobProperties
  examples/elasticjob-example-lite-java/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/JavaMain.java
Labels: example

#1357 Add Http job doc
  docs/content/faq/_index.cn.md
  docs/content/faq/_index.en.md
  docs/content/user-manual/elasticjob-lite/configuration/props.cn.md
  docs/content/user-manual/elasticjob-lite/configuration/props.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/job-interface.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/job-interface.en.md
  elasticjob-executor/elasticjob-executor-type/elasticjob-http-executor/src/main/java/org/apache/shardingsphere/elasticjob/http/executor/HttpJobExecutor.java
  elasticjob-executor/elasticjob-executor-type/elasticjob-http-executor/src/main/java/org/apache/shardingsphere/elasticjob/http/props/HttpJobProperties.java
Labels: document

#1370 Fix error data pattern
  elasticjob-infra/elasticjob-tracing/elasticjob-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/tracing/rdb/storage/RDBJobEventStorage.java
Labels: bug, tracing

#1372 update company list
  docs/content/powered-by/_index.cn.md
  docs/content/powered-by/_index.en.md
Labels: document

#1374 update company list
  docs/content/powered-by/_index.cn.md
  docs/content/powered-by/_index.en.md
Labels: document

#1380 Minor updates for code format and style
  elasticjob-api/src/main/java/org/apache/shardingsphere/elasticjob/api/JobDagConfiguration.java
  elasticjob-executor/elasticjob-executor-kernel/src/main/java/org/apache/shardingsphere/elasticjob/executor/ElasticJobExecutor.java
  elasticjob-infra/elasticjob-infra-common/src/main/java/org/apache/shardingsphere/elasticjob/infra/exception/DagRuntimeException.java
  elasticjob-infra/elasticjob-tracing/elasticjob-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/tracing/event/DagJobExecutionEvent.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/dag/DagNodeStorage.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/dag/DagStates.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/dag/JobRetryTrigger.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionService.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/state/JobStateEnum.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/state/JobStateNode.java
  elasticjob-lite/elasticjob-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/domain/DagBriefInfo.java
Labels: refactor

#1386 Update download page
  docs/content/downloads/_index.cn.md
  docs/content/downloads/_index.en.md
Labels: document

#1387 Update release date
  docs/content/downloads/_index.en.md
Labels: document

#1403 In Windows env, run ShardingSphere-ElasticJob-UI, could not find or …
  docs/content/faq/_index.cn.md
  docs/content/faq/_index.en.md
Labels: document

#1412 Add OneOffJob example
  examples/elasticjob-example-lite-java/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/JavaMain.java
Labels: example

#1414 Fix OneOffJob reschedule error
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/impl/OneOffJobBootstrap.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/RescheduleListenerManager.java
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobScheduleController.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobScheduleControllerTest.java
Labels: bug, kernel

#1420 Remove checking cron in JobConfigurationAPIImpl#updateJobConfiguration
  elasticjob-lite/elasticjob-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobConfigurationAPIImpl.java
Labels: bug, kernel
