Repository apache/shardingsphere-elasticjob, pull requests merged in 2020-05, with the labels that each got.

#592 Fixing flaky test ShutdownListenerManagerTest.assertIsShutdownAlready
  elastic-job-lite-core/src/test/java/io/elasticjob/lite/internal/instance/ShutdownListenerManagerTest.java
Labels: enhancement

#625 Fixing order-dependent tests
  elastic-job-lite-core/src/test/java/io/elasticjob/lite/api/JobSchedulerTest.java
  elastic-job-lite-core/src/test/java/io/elasticjob/lite/internal/schedule/JobRegistryTest.java
  elastic-job-lite-core/src/test/java/io/elasticjob/lite/internal/sharding/ExecutionServiceTest.java
Labels: test

#629 支持com.mysql.cj.jdbc.Driver
  elastic-job-lite-core/src/main/java/io/elasticjob/lite/event/rdb/JobEventRdbStorage.java
Labels: enhancement

#636 fixing order-dependence in ZookeeperRegistryCenterModifyTest
  elastic-job-lite-core/src/test/java/io/elasticjob/lite/reg/zookeeper/ZookeeperRegistryCenterModifyTest.java
Labels: test

#713 Show the trigger button
  elastic-job-lite-console/src/main/resources/console/js/status/job/jobs_status_overview.js
Labels: ui

#719 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  pom.xml
Labels: enhancement
