Repository apache/shardingsphere-elasticjob, pull requests merged in 2020-06, with the labels that each got.

#740 Update issue template
  .github/ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: document

#743 For #734, Translate elastic-job-lite-spring's java doc to English
  elastic-job-lite-spring/src/main/java/io/elasticjob/lite/spring/api/SpringJobScheduler.java
  elastic-job-lite-spring/src/main/java/io/elasticjob/lite/spring/job/handler/JobNamespaceHandler.java
  elastic-job-lite-spring/src/main/java/io/elasticjob/lite/spring/job/parser/common/AbstractJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/io/elasticjob/lite/spring/job/parser/common/BaseJobBeanDefinitionParserTag.java
  elastic-job-lite-spring/src/main/java/io/elasticjob/lite/spring/job/parser/dataflow/DataflowJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/io/elasticjob/lite/spring/job/parser/dataflow/DataflowJobBeanDefinitionParserTag.java
  elastic-job-lite-spring/src/main/java/io/elasticjob/lite/spring/job/parser/script/ScriptJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/io/elasticjob/lite/spring/job/parser/script/ScriptJobBeanDefinitionParserTag.java
  elastic-job-lite-spring/src/main/java/io/elasticjob/lite/spring/job/parser/simple/SimpleJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/io/elasticjob/lite/spring/job/util/AopTargetUtils.java
  elastic-job-lite-spring/src/main/java/io/elasticjob/lite/spring/reg/handler/RegNamespaceHandler.java
  elastic-job-lite-spring/src/main/java/io/elasticjob/lite/spring/reg/parser/ZookeeperBeanDefinitionParser.java
Labels: document

#745 Rename groupId to asf
  README.md
  README_ZH.md
  elastic-job-lite-console/pom.xml
  elastic-job-lite-core/pom.xml
  elastic-job-lite-lifecycle/pom.xml
  elastic-job-lite-spring/pom.xml
  pom.xml
Labels: build

#746 Fix checkstyle
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/context/TaskContext.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/event/JobEventListener.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/event/rdb/JobEventRdbIdentity.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/event/rdb/JobEventRdbSearch.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/event/rdb/JobEventRdbStorage.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/event/type/JobExecutionEvent.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/JobExecutorFactory.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/type/DataflowJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/type/ScriptJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/type/SimpleJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManager.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverNode.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/InstanceNode.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/ShutdownListenerManager.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/listener/RegistryCenterConnectionStateListener.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/reconcile/ReconcileService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobScheduleController.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobTriggerListener.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacade.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/SchedulerFacade.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/server/ServerNode.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/reg/base/ElectionCandidate.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/reg/zookeeper/ZookeeperElectionService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/reg/zookeeper/ZookeeperRegistryCenter.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/statistics/rdb/StatisticRdbRepository.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/config/ShardingItemParameters.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/digest/Encryption.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/json/AbstractJobConfigurationGsonTypeAdapter.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/handler/IgnoreJobExceptionHandler.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/handler/ThrowJobExceptionHandler.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/api/JobAPIFactory.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/api/ServerStatisticsAPI.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/domain/JobSettings.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/operate/JobOperateAPIImpl.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/operate/ShardingOperateAPIImpl.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImpl.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/JobStatisticsAPIImpl.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/ServerStatisticsAPIImpl.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/ShardingStatisticsAPIImpl.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/restful/RESTfulAPIExceptionMapper.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/handler/JobNamespaceHandler.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/common/AbstractJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/dataflow/DataflowJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/script/ScriptJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/simple/SimpleJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/util/AopTargetUtils.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/reg/parser/ZookeeperBeanDefinitionParser.java
Labels: refactor

#749 use apache maven info replace original elastic job info
  pom.xml
Labels: build

#752 Merge examples
  examples/.gitignore
  examples/LICENSE
  examples/README.md
  examples/elastic-job-example-cloud/pom.xml
  examples/elastic-job-example-cloud/src/README.txt
  examples/elastic-job-example-cloud/src/main/java/com/dangdang/ddframe/job/example/CloudJobMain.java
  examples/elastic-job-example-cloud/src/main/resources/META-INF/applicationContext.xml
  examples/elastic-job-example-cloud/src/main/resources/assembly/assembly.xml
  examples/elastic-job-example-cloud/src/main/resources/bin/start.sh
  examples/elastic-job-example-cloud/src/main/resources/logback.xml
  examples/elastic-job-example-cloud/src/main/resources/script/demo.sh
  examples/elastic-job-example-embed-zk/pom.xml
  examples/elastic-job-example-embed-zk/src/main/java/com/dangdang/ddframe/job/example/EmbedZookeeperServer.java
  examples/elastic-job-example-jobs/pom.xml
  examples/elastic-job-example-jobs/src/main/java/com/dangdang/ddframe/job/example/fixture/entity/Foo.java
  examples/elastic-job-example-jobs/src/main/java/com/dangdang/ddframe/job/example/fixture/repository/FooRepository.java
  examples/elastic-job-example-jobs/src/main/java/com/dangdang/ddframe/job/example/fixture/repository/FooRepositoryFactory.java
  examples/elastic-job-example-jobs/src/main/java/com/dangdang/ddframe/job/example/job/dataflow/JavaDataflowJob.java
  examples/elastic-job-example-jobs/src/main/java/com/dangdang/ddframe/job/example/job/dataflow/SpringDataflowJob.java
  examples/elastic-job-example-jobs/src/main/java/com/dangdang/ddframe/job/example/job/simple/JavaSimpleJob.java
  examples/elastic-job-example-jobs/src/main/java/com/dangdang/ddframe/job/example/job/simple/SpringSimpleJob.java
  examples/elastic-job-example-lite-java/pom.xml
  examples/elastic-job-example-lite-java/src/main/java/com/dangdang/ddframe/job/example/JavaMain.java
  examples/elastic-job-example-lite-java/src/main/resources/logback.xml
  examples/elastic-job-example-lite-java/src/main/resources/script/demo.bat
  examples/elastic-job-example-lite-java/src/main/resources/script/demo.sh
  examples/elastic-job-example-lite-spring/pom.xml
  examples/elastic-job-example-lite-spring/src/main/java/com/dangdang/ddframe/job/example/SpringMain.java
  examples/elastic-job-example-lite-spring/src/main/resources/META-INF/applicationContext.xml
  examples/elastic-job-example-lite-spring/src/main/resources/conf/job.properties
  examples/elastic-job-example-lite-spring/src/main/resources/conf/reg.properties
  examples/elastic-job-example-lite-spring/src/main/resources/logback.xml
  examples/elastic-job-example-lite-spring/src/main/resources/script/demo.bat
  examples/elastic-job-example-lite-spring/src/main/resources/script/demo.sh
  examples/elastic-job-example-lite-springboot/pom.xml
  examples/elastic-job-example-lite-springboot/src/main/java/com/dangdang/ddframe/job/example/SpringBootMain.java
  examples/elastic-job-example-lite-springboot/src/main/java/com/dangdang/ddframe/job/example/config/DataflowJobConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/com/dangdang/ddframe/job/example/config/JobEventConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/com/dangdang/ddframe/job/example/config/RegistryCenterConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/com/dangdang/ddframe/job/example/config/SimpleJobConfig.java
  examples/elastic-job-example-lite-springboot/src/main/resources/application-dev.yml
  examples/elastic-job-example-lite-springboot/src/main/resources/application-prod.yml
  examples/elastic-job-example-lite-springboot/src/main/resources/application.yml
  examples/elastic-job-example-lite-springboot/src/main/resources/logback.xml
  examples/pom.xml
Labels: example

#758 refine assembly
  elastic-job-lite-console/pom.xml
  elastic-job-lite-console/src/main/resources/assembly/assembly.xml
  pom.xml
Labels: build

#760 exclude files without license header
  pom.xml
Labels: licenses

#770 update resource url for docs
  docs/config.toml
  docs/content/00-overview/intro.md
  docs/content/02-guide/dump.md
  docs/content/03-design/lite-design.md
  docs/layouts/index.html
  docs/layouts/partials/logo.html
  docs/layouts/partials/style.html
  docs/themes/hugo-theme-learn/layouts/404.html
  docs/themes/hugo-theme-learn/layouts/partials/footer.html
  docs/themes/hugo-theme-learn/layouts/partials/header.html
  docs/themes/hugo-theme-learn/layouts/partials/search.html
Labels: document

#772 update asf.yaml for project tag
  .asf.yaml
Labels: build

#775 Translate dataflowJob description into English
  elastic-job-lite-spring/src/test/resources/conf/job/conf.properties
Labels: example

#779 revert maven-surefire-plugin
  pom.xml
Labels: build

#784 Fix Namespace URL error
  elastic-job-lite-spring/src/main/resources/META-INF/namespace/job.xsd
  elastic-job-lite-spring/src/main/resources/META-INF/namespace/reg.xsd
  elastic-job-lite-spring/src/main/resources/META-INF/spring.handlers
  elastic-job-lite-spring/src/main/resources/META-INF/spring.schemas
  elastic-job-lite-spring/src/test/resources/META-INF/job/base.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withEventTraceRdb.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withJobProperties.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withJobRef.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withListener.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withListenerAndCglib.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withListenerAndJdkDynamicProxy.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withoutListener.xml
  elastic-job-lite-spring/src/test/resources/META-INF/reg/regContext.xml
Labels: bug, spring

#793 Refactor miscellaneous
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/strategy/JobInstance.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/event/JobEventBus.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/JobExecutorFactory.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/handler/impl/DefaultExecutorServiceHandler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/type/DataflowJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/type/ScriptJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/type/SimpleJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJob.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/concurrent/ElasticJobExecutorService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/digest/Encryption.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/JobExecutorFactoryTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/SimpleJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/util/concurrent/ElasticJobExecutorServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/util/digest/EncryptionTest.java
  elastic-job-lite-spring/src/test/resources/META-INF/job/base.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withJobRef.xml
Labels: refactor

#794 Refactor spring namespace, avoid use extend JobScheduler
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/provided/InstanceProvidedDataflowJobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/provided/InstanceProvidedSimpleJobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/provided/JobInstanceProvided.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/json/AbstractJobConfigurationGsonTypeAdapter.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/api/SpringJobScheduler.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/common/AbstractJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/dataflow/DataflowJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/simple/SimpleJobBeanDefinitionParser.java
Labels: refactor, spring

#795 Avoid inner class import
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/json/AbstractJobConfigurationGsonTypeAdapter.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/config/JobCoreConfigurationTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/handler/JobPropertiesTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/config/TestDataflowJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/config/TestScriptJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/config/TestSimpleJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/AbstractBaseStdJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/LiteJobConfigurationGsonFactoryTest.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImpl.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/common/AbstractJobBeanDefinitionParser.java
Labels: refactor

#799 Refactor Spring namespace
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/JobSchedulerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/AbstractBaseStdJobTest.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/common/AbstractJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/dataflow/DataflowJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/simple/SimpleJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/resources/META-INF/namespace/job.xsd
  elastic-job-lite-spring/src/test/resources/META-INF/job/withEventTraceRdb.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withJobProperties.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withJobRef.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withListener.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withListenerAndCglib.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withListenerAndJdkDynamicProxy.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withoutListener.xml
  elastic-job-lite-spring/src/test/resources/conf/job/conf.properties
Labels: API, refactor

#800 Upgrade example version
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  examples/elastic-job-example-embed-zk/pom.xml
  examples/elastic-job-example-jobs/pom.xml
  examples/elastic-job-example-jobs/src/main/java/com/dangdang/ddframe/job/example/job/dataflow/JavaDataflowJob.java
  examples/elastic-job-example-jobs/src/main/java/com/dangdang/ddframe/job/example/job/dataflow/SpringDataflowJob.java
  examples/elastic-job-example-jobs/src/main/java/com/dangdang/ddframe/job/example/job/simple/JavaSimpleJob.java
  examples/elastic-job-example-jobs/src/main/java/com/dangdang/ddframe/job/example/job/simple/SpringSimpleJob.java
  examples/elastic-job-example-lite-java/pom.xml
  examples/elastic-job-example-lite-java/src/main/java/com/dangdang/ddframe/job/example/JavaMain.java
  examples/elastic-job-example-lite-spring/pom.xml
  examples/elastic-job-example-lite-springboot/pom.xml
  examples/elastic-job-example-lite-springboot/src/main/java/com/dangdang/ddframe/job/example/config/DataflowJobConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/com/dangdang/ddframe/job/example/config/JobEventConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/com/dangdang/ddframe/job/example/config/RegistryCenterConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/com/dangdang/ddframe/job/example/config/SimpleJobConfig.java
  examples/pom.xml
Labels: example

#802 Remove class name for job configuration
  elastic-job-lite-console/src/main/resources/console/html/status/job/job_config.html
  elastic-job-lite-console/src/main/resources/console/js/status/job/job_config.js
  elastic-job-lite-console/src/main/resources/console/js/status/job/jobs_status_overview.js
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/JobTypeConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/dataflow/DataflowJobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/script/ScriptJobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/simple/SimpleJobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/SchedulerFacade.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/storage/JobNodeStorage.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/json/AbstractJobConfigurationGsonTypeAdapter.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/JobSchedulerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/config/LiteJobConfigurationTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/APIJsonConstants.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/LiteJsonConstants.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/config/TestDataflowJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/config/TestSimpleJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/util/JobConfigurationUtil.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/AbstractBaseStdJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/LiteJobConfigurationGsonFactoryTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/reconcile/ReconcileServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/SchedulerFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionContextServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingServiceTest.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/domain/JobSettings.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImpl.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/fixture/LifecycleJsonConstants.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImplTest.java
  examples/elastic-job-example-lite-java/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/JavaMain.java
  examples/elastic-job-example-lite-spring/src/main/resources/META-INF/applicationContext.xml
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/DataflowJobConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/SimpleJobConfig.java
Labels: API, refactor

#803 Remove JobInstanceProvided
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/provided/InstanceProvidedDataflowJobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/provided/InstanceProvidedSimpleJobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/provided/JobInstanceProvided.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/json/AbstractJobConfigurationGsonTypeAdapter.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/dataflow/DataflowJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/simple/SimpleJobBeanDefinitionParser.java
Labels: refactor, spring

#805 Use SPI to introduce job sharding strategy
  docs/content/02-guide/config-manual.md
  docs/content/02-guide/job-sharding-strategy.md
  elastic-job-lite-console/src/main/resources/console/html/status/job/job_config.html
  elastic-job-lite-console/src/main/resources/console/i18n/message_en.properties
  elastic-job-lite-console/src/main/resources/console/i18n/message_zh.properties
  elastic-job-lite-console/src/main/resources/console/js/status/job/job_config.js
  elastic-job-lite-console/src/main/resources/console/js/status/job/jobs_status_overview.js
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/strategy/JobShardingStrategy.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/strategy/JobShardingStrategyFactory.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/strategy/impl/AverageAllocationJobShardingStrategy.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/strategy/impl/OdevitySortByNameJobShardingStrategy.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/strategy/impl/RoundRobinByNameJobShardingStrategy.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/LiteJobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/LiteJobConfigurationConstants.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/LiteJobConfigurationGsonFactory.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingService.java
  elastic-job-lite-core/src/main/resources/META-INF/services/org.apache.shardingsphere.elasticjob.lite.api.strategy.JobShardingStrategy
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/strategy/JobShardingStrategyFactoryTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/strategy/fixture/InvalidJobShardingStrategy.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/strategy/impl/RotateServerByNameJobShardingStrategyTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/config/LiteJobConfigurationTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/LiteJsonConstants.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/LiteJobConfigurationGsonFactoryTest.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/domain/JobSettings.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImpl.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/fixture/LifecycleJsonConstants.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImplTest.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/common/AbstractJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/common/BaseJobBeanDefinitionParserTag.java
  elastic-job-lite-spring/src/main/resources/META-INF/namespace/job.xsd
Labels: API, refactor

#806 Add default job sharding strategy
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/strategy/JobShardingStrategyFactory.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/strategy/JobShardingStrategyFactoryTest.java
Labels: refactor

#809 Rename JobExceptionHandler to JobErrorHandler
  docs/content/02-guide/config-manual.md
  docs/content/02-guide/customized-hook.md
  elastic-job-lite-console/src/main/resources/console/html/status/job/job_config.html
  elastic-job-lite-console/src/main/resources/console/i18n/message_en.properties
  elastic-job-lite-console/src/main/resources/console/i18n/message_zh.properties
  elastic-job-lite-console/src/main/resources/console/js/status/job/job_config.js
  elastic-job-lite-console/src/main/resources/console/js/status/job/jobs_status_overview.js
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/JobCoreConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/handler/error/JobErrorHandler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/handler/error/JobErrorHandlerFactory.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/handler/error/impl/IgnoreJobErrorHandler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/handler/error/impl/LogJobErrorHandler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/handler/error/impl/ThrowJobErrorHandler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/handler/error/impl/ThrowJobExceptionHandler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/json/AbstractJobConfigurationGsonTypeAdapter.java
  elastic-job-lite-core/src/main/resources/META-INF/services/org.apache.shardingsphere.elasticjob.lite.executor.handler.error.JobErrorHandler
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/config/JobCoreConfigurationTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/handler/error/impl/LogJobErrorHandlerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/SimpleJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/APIJsonConstants.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/config/TestDataflowJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/config/TestScriptJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/config/TestSimpleJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/AbstractBaseStdJobTest.java
  elastic-job-lite-core/src/test/resources/logback-test.xml
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/domain/JobSettings.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImpl.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/common/AbstractJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/common/BaseJobBeanDefinitionParserTag.java
  elastic-job-lite-spring/src/main/resources/META-INF/namespace/job.xsd
  elastic-job-lite-spring/src/test/resources/META-INF/job/withEventTraceRdb.xml
  elastic-job-lite-spring/src/test/resources/META-INF/job/withJobHandler.xml
Labels: API, refactor

#814 Add impl package for org.apache.shardingsphere.elasticjob.lite.executor.type
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/JobExecutorFactory.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/DataflowJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/ScriptJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/SimpleJobExecutor.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/JobExecutorFactoryTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/DataflowJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/ElasticJobVerify.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/ScriptJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/SimpleJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/WrongJobExecutorTest.java
Labels: refactor

#819 Use runner instead of MockitoAnnotations.initMocks(this)
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/JobSchedulerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/listener/DistributeOnceElasticJobListenerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/handler/sharding/JobInstanceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/AbstractBaseStdJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/LiteJobConfigurationGsonFactoryTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/RescheduleListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/election/ElectionListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/election/LeaderServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/InstanceServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/ShutdownListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/TriggerListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/listener/ListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/listener/RegistryCenterConnectionStateListenerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/reconcile/ReconcileServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobScheduleControllerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobTriggerListenerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/SchedulerFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/server/ServerServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionContextServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/MonitorExecutionListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/storage/JobNodeStorageTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/util/env/HostExceptionTest.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/operate/JobOperateAPIImplTest.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/operate/ShardingOperateAPIImplTest.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImplTest.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/JobStatisticsAPIImplTest.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/ServerStatisticsAPIImplTest.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/ShardingStatisticsAPIImplTest.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/restful/RestfulServerTest.java
Labels: test

#821 Remove unitils dependency
  elastic-job-lite-console/pom.xml
  elastic-job-lite-core/pom.xml
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/JobSchedulerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/listener/DistributeOnceElasticJobListenerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/event/JobEventBusTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/event/rdb/JobEventRdbListenerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/SimpleJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/util/JobConfigurationUtil.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/AbstractBaseStdJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/OneOffDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobForExecuteFailureTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobForExecuteThrowsExceptionTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobForMultipleThreadsTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobForNotMonitorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/RescheduleListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/election/ElectionListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/election/LeaderServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/InstanceServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/ShutdownListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/instance/TriggerListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/listener/ListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/listener/RegistryCenterConnectionStateListenerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/reconcile/ReconcileServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobRegistryTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobScheduleControllerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/SchedulerFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/server/ServerServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionContextServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/MonitorExecutionListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/storage/JobNodeStorageTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/util/ReflectionUtils.java
  pom.xml
Labels: test

#823 Refactor miscellaneous
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/event/JobEventBus.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/AbstractBaseStdJobTest.java
Labels: refactor

#824 Simplify ShardingContexts
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ShardingContexts.java
Labels: refactor

#826 Move statistic to elastic-job-lite-tracing-rdb
  elastic-job-lite-core/pom.xml
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/statistics/StatisticInterval.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/statistics/rdb/StatisticRdbRepository.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/statistics/type/job/JobExecutionTypeStatistics.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/statistics/type/job/JobRegisterStatistics.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/statistics/type/job/JobRunningStatistics.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/statistics/type/job/JobTypeStatistics.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/statistics/type/task/TaskResultStatistics.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/statistics/type/task/TaskRunningStatistics.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/statistics/rdb/StatisticRdbRepositoryTest.java
Labels: refactor

#827 Refactor tracing package
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/restful/EventTraceHistoryRESTfulAPI.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/JobFacade.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacade.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/ElasticJobVerify.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/SimpleJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/WrongJobExecutorTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/JobEvent.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/JobEventBus.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/config/JobEventConfiguration.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/event/JobEvent.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/event/JobExecutionEvent.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/event/JobStatusTraceEvent.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/exception/TracingConfigurationException.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/listener/JobEventListener.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/JobEventBusTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/event/JobExecutionEventTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/fixture/TestJobEventConfiguration.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/fixture/TestJobEventFailureConfiguration.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/fixture/TestJobEventListener.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/JobEventRdbConfiguration.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/JobEventRdbSearch.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/JobEventRdbStorage.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/JobEventRdbConfigurationTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/JobEventRdbListenerTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/JobEventRdbSearchTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/JobEventRdbStorageTest.java
  examples/elastic-job-example-lite-java/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/JavaMain.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/DataflowJobConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/JobEventConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/SimpleJobConfig.java
Labels: refactor

#829 Remove useless JobEventIdentity
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/JobEventIdentity.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/config/JobEventConfiguration.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/listener/JobEventListener.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/fixture/TestJobEventConfiguration.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/fixture/TestJobEventFailureConfiguration.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/fixture/TestJobEventIdentity.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/fixture/TestJobEventListener.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/JobEventRdbIdentity.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/config/JobEventRdbConfiguration.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/listener/JobEventRdbListener.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/JobEventRdbIdentityTest.java
Labels: refactor, tracing

#830 Rename TracingConfiguration and TracingListener
  docs/content/02-guide/event-trace.md
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/common/AbstractJobBeanDefinitionParser.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/JobEventBus.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/config/TracingConfiguration.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/listener/TracingListener.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/JobEventBusTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/event/JobExecutionEventTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/fixture/TestTracingConfiguration.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/fixture/TestTracingFailureConfiguration.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/fixture/TestTracingListener.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/resources/logback-test.xml
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/config/RDBTracingConfiguration.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/listener/RDBTracingListener.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/config/RDBTracingConfigurationTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/listener/RDBTracingListenerTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/search/JobEventRdbSearchTest.java
  examples/elastic-job-example-lite-java/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/JavaMain.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/DataflowJobConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/JobEventConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/SimpleJobConfig.java
Labels: refactor

#832 Remove default tracing listener
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/listener/TracingListenerFactory.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/listener/TracingListenerFactoryTest.java
Labels: refactor, tracing

#833 Unify RDB module
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/restful/EventTraceHistoryRESTfulAPI.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/listener/RDBTracingListener.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/search/RDBJobEventSearch.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/statistics/rdb/RDBStatisticRepository.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/storage/RDBJobEventStorage.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/listener/RDBTracingListenerTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/search/RDBJobEventSearchTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/statistics/rdb/RDBStatisticRepositoryTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/storage/RDBJobEventStorageTest.java
Labels: refactor, tracing

#834 Use properties to provide SQL on RDBJobEventStorage
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/DatabaseType.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/storage/RDBJobEventStorage.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/storage/RDBStorageSQLMapper.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/resources/META-INF/sql/storage/mysql.properties
Labels: refactor, tracing

#835 Move search & statistics to elastic-job-lite-console module
  elastic-job-lite-console/pom.xml
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearch.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/StatisticInterval.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/rdb/RDBStatisticRepository.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/type/job/JobExecutionTypeStatistics.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/type/job/JobRegisterStatistics.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/type/job/JobRunningStatistics.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/type/job/JobTypeStatistics.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/type/task/TaskResultStatistics.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/type/task/TaskRunningStatistics.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/restful/EventTraceHistoryRESTfulAPI.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearchTest.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/rdb/RDBStatisticRepositoryTest.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/storage/RDBJobEventStorage.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/storage/RDBStorageSQLMapper.java
Labels: refactor, tracing

#839 Use dialect to distinguish SQL
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/DatabaseType.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/storage/RDBJobEventStorage.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/storage/RDBStorageSQLMapper.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/type/DatabaseType.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/type/impl/DB2DatabaseType.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/type/impl/H2DatabaseType.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/type/impl/MySQLDatabaseType.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/type/impl/OracleDatabaseType.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/type/impl/PostgreSQLDatabaseType.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/rdb/type/impl/SQLServerDatabaseType.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/resources/META-INF/services/org.apache.shardingsphere.elasticjob.lite.tracing.rdb.type.DatabaseType
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/resources/META-INF/sql/h2.properties
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/resources/META-INF/sql/mysql.properties
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/src/main/resources/META-INF/sql/sql92.properties
Labels: refactor, tracing

#842 Remove MySQL dependency
  elastic-job-lite-tracing/elastic-job-lite-tracing-rdb/pom.xml
  pom.xml
Labels: refactor, tracing

#845 Remove JobExecutorFactory
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/JobExecutorFactory.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJob.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/JobExecutorFactoryTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/DataflowJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/ScriptJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/SimpleJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/WrongJobExecutorTest.java
Labels: refactor

#844 Fixed start script for Windows
  elastic-job-lite-console/src/main/resources/bin/start.bat
Labels: bug, console

#846 Remove unreasonable test fixture implementation of JobRootConfiguration
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/LiteJobConfigurationGsonFactory.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/DataflowJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/ScriptJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/SimpleJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/WrongJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/config/TestDataflowJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/config/TestJobRootConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/config/TestScriptJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/config/TestSimpleJobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/util/json/JobConfigurationGsonTypeAdapterTest.java
Labels: test

#848 Use enum and reflect to simplify JSON processor
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/LiteJobConfigurationConstants.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/LiteJobConfigurationGsonFactory.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/RescheduleListenerManager.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/json/JobConfigurationJsonEnum.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/json/LiteJobConfigurationGsonFactory.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/json/LiteJobConfigurationGsonTypeAdapter.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManager.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/MonitorExecutionListenerManager.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingListenerManager.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/json/AbstractJobConfigurationGsonTypeAdapter.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/AbstractBaseStdJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/script/ScriptElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/LiteJobConfigurationGsonFactoryTest.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImpl.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/JobStatisticsAPIImpl.java
Labels: refactor

#850 Simplify Job API level, merge configuration object to single
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/JobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/JobCoreConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/JobTypeConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/dataflow/DataflowJobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/script/ScriptJobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/simple/SimpleJobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/DataflowJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/ScriptJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/RescheduleListenerManager.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/json/JobConfigurationGsonTypeAdapter.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/json/JobConfigurationJsonEnum.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacade.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionContextService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingListenerManager.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingService.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/JobSchedulerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/config/JobConfigurationTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/config/JobCoreConfigurationTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/DataflowJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/ScriptJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/SimpleJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/WrongJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/util/JobConfigurationUtil.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/AbstractBaseStdJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/OneOffDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobForExecuteFailureTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobForExecuteThrowsExceptionTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobForMultipleThreadsTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobForNotMonitorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/script/ScriptElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/JobConfigurationGsonFactoryTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/guarantee/GuaranteeServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/reconcile/ReconcileServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/SchedulerFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionContextServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ExecutionServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingServiceTest.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImpl.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/JobStatisticsAPIImpl.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/common/AbstractJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/dataflow/DataflowJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/script/ScriptJobBeanDefinitionParser.java
  elastic-job-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/job/parser/simple/SimpleJobBeanDefinitionParser.java
  examples/elastic-job-example-lite-java/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/JavaMain.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/DataflowJobConfig.java
  examples/elastic-job-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/config/SimpleJobConfig.java
Labels: API, refactor

#851 Modify jobShardingStrategyType's init value from empty string to null
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/config/JobConfiguration.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/config/JobConfigurationTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/JobConfigurationGsonFactoryTest.java
Labels: refactor

#853 Use YAML instead of JSON for job persist
  elastic-job-lite-core/pom.xml
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/RescheduleListenerManager.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/json/JobConfigurationGsonFactory.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/json/JobConfigurationGsonTypeAdapter.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/json/JobConfigurationJsonEnum.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/yaml/YamlJobConfiguration.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManager.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/MonitorExecutionListenerManager.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingListenerManager.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/yaml/DefaultYamlTupleProcessor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/yaml/ElasticJobYamlRepresenter.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/util/yaml/YamlEngine.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/LiteJsonConstants.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/AbstractBaseStdJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobForExecuteFailureTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobForExecuteThrowsExceptionTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobForMultipleThreadsTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/dataflow/StreamingDataflowElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/integrate/std/script/ScriptElasticJobTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/JobConfigurationGsonFactoryTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/RescheduleListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/yaml/YamlJobConfigurationTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/MonitorExecutionListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/reg/zookeeper/ZookeeperRegistryCenterQueryWithoutCacheTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/util/yaml/YamlEngineTest.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/domain/JobSettings.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImpl.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/JobStatisticsAPIImpl.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/fixture/LifecycleJsonConstants.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImplTest.java
  pom.xml
Labels: refactor

#856 Minor updates
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/security/WwwAuthFilter.java
  elastic-job-lite-tracing/elastic-job-lite-tracing-api/src/main/java/org/apache/shardingsphere/elasticjob/lite/tracing/event/JobExecutionEvent.java
Labels: refactor

#857 Update json to yaml
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/APIJsonConstants.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/fixture/LiteYamlConstants.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/RescheduleListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/failover/FailoverListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/MonitorExecutionListenerManagerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/sharding/ShardingListenerManagerTest.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/JobStatisticsAPIImpl.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/fixture/LifecycleYamlConstants.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/settings/JobSettingsAPIImplTest.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/JobStatisticsAPIImplTest.java
Labels: refactor

#854 Use spring boot to refactor elastic-job-lite-console
  elastic-job-lite-console/pom.xml
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/config/FilterRegisterConfig.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/config/WebMvcConfig.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/EventTraceDataSourceController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/EventTraceHistoryController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/JobConfigController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/JobOperationController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/RegistryCenterController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/ServerOperationController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/filter/GlobalConfigurationFilter.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/restful/EventTraceHistoryRESTfulAPI.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/security/AuthenticationResult.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/security/UserAuthenticationService.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/security/WwwAuthFilter.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/impl/EventTraceDataSourceConfigurationServiceImpl.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/impl/JobAPIServiceImpl.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/impl/RegistryCenterConfigurationServiceImpl.java
  elastic-job-lite-console/src/main/resources/application.properties
  elastic-job-lite-console/src/main/resources/assembly/assembly.xml
  elastic-job-lite-console/src/main/resources/bin/start.bat
  elastic-job-lite-console/src/main/resources/bin/start.sh
  elastic-job-lite-lifecycle/pom.xml
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/restful/RESTfulAPIServer.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/restful/RestfulServerTest.java
  elastic-job-lite-lifecycle/src/test/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/restful/fixture/TestFilter.java
  pom.xml
Labels: console

#859 Update for README
  README.md
  README_ZH.md
Labels: document

#861 Redesign ElasticJobExecutor, avoid use JobFacade as input param
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJob.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacade.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/DataflowJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/ScriptJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/SimpleJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/executor/type/impl/WrongJobExecutorTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/LiteJobFacadeTest.java
Labels: refactor

#863 Add Dockerfile for console
  elastic-job-lite-console/.dockerignore
  elastic-job-lite-console/Dockerfile
Labels: build

#865 Code format for elastic-job-lite-console
  elastic-job-lite-console/.dockerignore
  elastic-job-lite-console/Dockerfile
  elastic-job-lite-console/pom.xml
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/ConsoleBootstrap.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/config/FilterRegisterConfig.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/config/WebMvcConfig.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/EventTraceDataSourceController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/EventTraceHistoryController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/JobConfigController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/JobOperationController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/RegistryCenterController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/controller/ServerOperationController.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearch.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/dao/statistics/rdb/RDBStatisticRepository.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/domain/EventTraceDataSourceFactory.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/filter/GlobalConfigurationFilter.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/repository/impl/AbstractXmlRepositoryImpl.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/security/AuthenticationResult.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/security/UserAuthenticationService.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/security/WwwAuthFilter.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/EventTraceDataSourceConfigurationService.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/JobAPIService.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/RegistryCenterConfigurationService.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/impl/EventTraceDataSourceConfigurationServiceImpl.java
  elastic-job-lite-console/src/main/java/org/apache/shardingsphere/elasticjob/lite/console/service/impl/RegistryCenterConfigurationServiceImpl.java
  elastic-job-lite-console/src/test/java/org/apache/shardingsphere/elasticjob/lite/console/dao/search/RDBJobEventSearchTest.java
Labels: console, refactor

#864 update some version
  elastic-job-lite-spring/pom.xml
  examples/elastic-job-example-lite-springboot/pom.xml
  examples/pom.xml
  pom.xml
Labels: build

#870 Remove duplicate code in constructor
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
Labels: refactor

#874 Add SetUpFacade
  elastic-job-lite-console/src/main/resources/bin/start.sh
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/JobScheduler.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/executor/ElasticJobExecutor.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationService.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobShutdownHookPlugin.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/SchedulerFacade.java
  elastic-job-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/SetUpFacade.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/api/JobSchedulerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/config/ConfigurationServiceTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/listener/JobListenerTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/SchedulerFacadeTest.java
  elastic-job-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/SetUpFacadeTest.java
  elastic-job-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/ServerStatisticsAPIImpl.java
Labels: refactor
