Repository apache/shardingsphere-elasticjob, pull requests merged in 2020-11, with the labels that each got.

#1687 Exclude .flattened-pom.xml from src distribution
  elasticjob-distribution/elasticjob-src-distribution/src/main/assembly/source-distribution.xml
Labels: build

#1692 Fix distribute once listener may cause deadlock when all servers are disabled
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/listener/AbstractDistributeOnceElasticJobListener.java
Labels: enhancement, lite

#1693 Update download page
  docs/content/downloads/_index.cn.md
  docs/content/downloads/_index.en.md
Labels: document, release

#1699 Update release note
  RELEASE-NOTES.md
Labels: release

#1700 Update .asf.yaml to sync features
  .asf.yaml
Labels: document

#1704 update all license for cloud-scheduler-distribution
  elasticjob-distribution/elasticjob-cloud-scheduler-distribution/src/main/release-docs/LICENSE
  elasticjob-distribution/elasticjob-cloud-scheduler-distribution/src/main/release-docs/licenses/LICENSE-checker-framework.txt
  elasticjob-distribution/elasticjob-cloud-scheduler-distribution/src/main/release-docs/licenses/LICENSE-jakarta.txt
  elasticjob-distribution/elasticjob-cloud-scheduler-distribution/src/main/release-docs/licenses/LICENSE-mchange-commons.txt
  pom.xml
Labels: build

#1701 Update required Maven version in enforcer rules
  pom.xml
Labels: build

#1703 Adjust the timing of configuring ElasticJob in Spring Boot startup process
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/boot/job/ElasticJobBootstrapConfiguration.java
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/boot/job/ElasticJobLiteAutoConfiguration.java
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/boot/job/ScheduleJobBootstrapStartupRunner.java
Labels: enhancement, lite, spring

#1708 Update documents and examples of Spring Boot Starter
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-boot-starter.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-boot-starter.en.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-namespace.cn.md
  docs/content/user-manual/elasticjob-lite/usage/job-api/spring-namespace.en.md
  examples/elasticjob-example-lite-spring/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/SpringMain.java
  examples/elasticjob-example-lite-spring/src/main/resources/META-INF/application-context.xml
  examples/elasticjob-example-lite-springboot/src/main/java/org/apache/shardingsphere/elasticjob/lite/example/controller/OneOffJobController.java
Labels: document, example

#1709 Unify dependencies' version and exclude unnecessary dependencies
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/pom.xml
  pom.xml
Labels: dependencies

#1711 update license for cloud-scheduler-distribution
  elasticjob-distribution/elasticjob-cloud-scheduler-distribution/src/main/release-docs/LICENSE
Labels: licenses

#1719 Update contents about Cloud Scheduler in FAQ
  docs/content/faq/_index.cn.md
  docs/content/faq/_index.en.md
Labels: cloud, document

#1717 Update version
  examples/pom.xml
  pom.xml
Labels: example

#1718 Move flatten-maven-plugin from pluginManagement to plugins in examples
  examples/pom.xml
Labels: dependencies

#1713 Release HTTP request after handling
  elasticjob-infra/elasticjob-restful/src/main/java/org/apache/shardingsphere/elasticjob/restful/NettyRestfulService.java
  elasticjob-infra/elasticjob-restful/src/main/java/org/apache/shardingsphere/elasticjob/restful/pipeline/HandleMethodExecutor.java
  elasticjob-infra/elasticjob-restful/src/main/java/org/apache/shardingsphere/elasticjob/restful/pipeline/HttpRequestDispatcher.java
Labels: RESTFul, enhancement

#1722 Adjust delay for HttpJobExecutorTest
  elasticjob-ecosystem/elasticjob-executor/elasticjob-executor-type/elasticjob-http-executor/src/test/java/org/apache/shardingsphere/elasticjob/http/executor/fixture/InternalController.java
Labels: test

#1723 Correct mistakes in Javadoc
  elasticjob-api/src/main/java/org/apache/shardingsphere/elasticjob/api/JobConfiguration.java
  elasticjob-infra/elasticjob-infra-common/src/main/java/org/apache/shardingsphere/elasticjob/infra/handler/sharding/JobShardingStrategy.java
  elasticjob-infra/elasticjob-infra-common/src/main/java/org/apache/shardingsphere/elasticjob/infra/handler/sharding/JobShardingStrategyFactory.java
Labels: enhancement

#1727 Update company list
  docs/content/powered-by/_index.cn.md
  docs/content/powered-by/_index.en.md
Labels: document

#1729 Increase testcases' coverage of module elasticjob-lite-spring-boot-starter
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/test/java/org/apache/shardingsphere/elasticjob/lite/spring/boot/job/ElasticJobConfigurationPropertiesTest.java
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/test/java/org/apache/shardingsphere/elasticjob/lite/spring/boot/job/ElasticJobSpringBootTest.java
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/test/java/org/apache/shardingsphere/elasticjob/lite/spring/boot/reg/ZookeeperPropertiesTest.java
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/test/java/org/apache/shardingsphere/elasticjob/lite/spring/boot/reg/snapshot/ElasticJobSnapshotServiceConfigurationTest.java
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/test/resources/application-elasticjob.yml
  elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/test/resources/application-snapshot.yml
Labels: test

#1734 Add null check in SnapshotService to avoid NPE
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SnapshotService.java
Labels: enhancement, lite

#1738 Polish SnapshotService
  elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SnapshotService.java
  elasticjob-lite/elasticjob-lite-core/src/test/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SnapshotServiceDisableTest.java
Labels: lite, refactor

#1740 Override close method for implementations of JobErrorHandler
  elasticjob-ecosystem/elasticjob-error-handler/elasticjob-error-handler-type/elasticjob-error-handler-dingtalk/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/dingtalk/DingtalkJobErrorHandler.java
  elasticjob-ecosystem/elasticjob-error-handler/elasticjob-error-handler-type/elasticjob-error-handler-wechat/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/wechat/WechatJobErrorHandler.java
Labels: lite, refactor
